### ISSUE TITLE
Extension Architecture: TOC nesting wrong

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#102]
The TOC nesting on the "Extension Architecture" page is wrong:

![2016-12-23 auswahl_001](https://cloud.githubusercontent.com/assets/59036/21450587/c797f90c-c8f8-11e6-9feb-b3833c7c4431.png)

Not everything should be childs of "Introduction".

https://docs.typo3.org/typo3cms/CoreApiReference/latest/ExtensionArchitecture/Index.html

**Comment by marble** [comment]
Thanks for reporting. I just fixed it for this case. I'm afraid there are a lot more. To fix that, documents have to be restructured a bit, as documents that are pulled in by the toctree directive are always subordninat to the section that pulls them in. If you see more problems like this please create an issue. It's enough to copy the link to the page and report an "hierarchy error". Thanks and happy christmas!
