### ISSUE TITLE
Extbase: Explain under which circumstances validations are triggered

### ISSUE THREAD

**Issue by moe2k** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1056]
Explain a little more in-depth when and under what circumstances validation happen:

- Validators are triggered if the property mapper has to convert an argument's source value into the desired target value
- If the source value already matches the target type (for example if you pass an object to a controllerAction from another action using forward()), validators are not called

People often wonder why validators aren’t called although they made controller annotations.

**Comment by linawolf** [comment]
@moe2k can you make a PR about this?

**Comment by linawolf** [comment]
no reaction within a month
