### ISSUE TITLE
Explain Property Mapper Configuration

### ISSUE THREAD

**Issue by moe2k** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1057]
https://docs.typo3.org/m/typo3/book-extbasefluid/10.4/en-us/10-Outlook/4-Property-mapping.html

- Add example / best practice where/how to configure the property mapper (initializeAction?)
- Explanation of options (allowCreation vs. allowModification, allowProperties, allowAll, allowExcept, setTypeConverter, etc.)
- Explain that data from external forms (not TYPO3) is not trusted unless you allow it

**Comment by linawolf** [comment]
@moe2k can you make a PR about this?

**Comment by linawolf** [comment]
No reaction within a month
