### ISSUE TITLE
Explain custom type converters with configuration

### ISSUE THREAD

**Issue by moe2k** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1058]
https://docs.typo3.org/m/typo3/book-extbasefluid/10.4/en-us/10-Outlook/4-Property-mapping.html

- Explain use cases for a custom type converter, and when to avoid it
- Explain difference between a registered type converter which is considered every time source and target match, and an unregistered typeConverter which will only be used manually or if configured in the property mapper

Maybe this can act as a start if helmut is fine with that: https://gist.github.com/helhum/58a406fbb846b56a8b50

- explain how to pass configuration to a type converter
- explain type converter priority
- Add an example for a custom type converter
- Explain what happens if a type converter returns an Error (vs. an Exception or the target type)

**Comment by linawolf** [comment]
@moe2k can you make a PR about this?

**Comment by linawolf** [comment]
No reaction within a month
