### ISSUE TITLE
Explain the difference between the “core” queryBuilder and the one used in extbase repository context

### ISSUE THREAD

**Issue by moe2k** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1059]
Explain the difference between the concepts and how they relate to each other

**Comment by sypets** [comment]
awesome. That has been bugging me for a while that that was not clarified anywhere. 

@moe2k If you could jot down some notes here, what the text should include, that might be helpful.

---

Related: 

I would go even further: There are several other areas where you can use Extbase or not (e.g. backend modules). See also #1060

There is currently no place in the docs which clarify the various ways to do things and gives the beginner an overview. This also goes for other areas, e.g. scheduler vs command controller, sys_log vs logging framework, "old" TYPO3 configuration methods vs using Yaml, Extbase or not etc. 

I am not sure if this should go in "TYPO3 Explained", though. (We keep stuffing more and more into it). "TYPO3 Explained" is currently a list of various topics. Possibly a more tutorial like manual might be created, which actually walks beginners through getting started with extension development, see https://github.com/TYPO3-Documentation/DocsTypo3Org-Homepage/issues/149

**Comment by linawolf** [comment]
@moe2k can you make a PR about this?

**Comment by moe2k** [comment]
Unfortunately I'm so busy at the moment that I'm afraid I won't be able do deliver something in the next months. So if you want to go ahed, don't wait for me.

**Comment by linawolf** [comment]
Ok, so it seems like we have none who could do this.
