### ISSUE TITLE
Explain when to use Extbase and when not

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1060]
There are several ways to do things, e.g.

* create backend modules with Extbase or without
* use Extbase persistence framework or QueryBuilder directly

The "Extbase / Fluid" way to create plugins used to be propagated as _the_ way to create extensions. It is not the only way and it is a good choice for some usecases and not for others.

There was actually a session about this topic a while ago at a barcamp in Hamburg. The topic keeps coming up. 

I think for beginners, this is very confusing, because there is not a very good getting started resource for developers

Related: 

* #1059
* https://github.com/TYPO3-Documentation/DocsTypo3Org-Homepage/issues/149

**Comment by linawolf** [comment]
I think this is a topic of taste. Not so easy to make recommendations. How could we resolve this?

**Comment by remonator** [comment]
I'm still confused about how, when or whether at all to use `AbstractPlugin` as it seems there are no clear instructions on this [in the docs](https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ApiOverview/ContentElements/CreatePlugins.html)

**Comment by linawolf** [comment]
noone took charge of this issue, unfortunary
