### ISSUE TITLE
Remove section "Migrated Files" in recent versions?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1075]
When FAL was introduced (in 6) some files were moved to fileadmin/_migrated.

Is the folder `_migrated` still relevant for newer TYPO3 versions?

**Comment by fsaris** [comment]
As far as I can remember this is not relevant anymore

**Comment by fsaris** [comment]
Was part of the migration process of moving from `uploads` to `fileadmin` https://docs.typo3.org/m/typo3/reference-fal/6.2/en-us/Administrators/Upgrading/Index.html

**Comment by DavidBruchmann** [comment]
In larger updates across several versions it's common to have that folder. The files can be moved somewhere else in the file-tree but that must be done then in TYPO3 to keep the relations in the database.  
Probably the folder is not related to versions 6-10 but to upgrades from 4 to 6 though.
