### ISSUE TITLE
Update "Soft References"

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1076]
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/SoftReferences/Index.html

* Using the  `<link>` tag is obsolete: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Deprecation-83252-Link-tagSyntaxProcesssing.html
* explain format "<a href="t3://page?uid=163#275">link</a>"
* what is a "typolink"
* typolink_tag: "As typolink, but searching for a <link> tag encapsulating it." - how so, if `<link>` is deprecated?
* Possibly show an example for each type how the links looks in code
* "images from `upload/.`" - is /upload still relevant?
* description "Email highlight." is a little vague 
* ...

**Comment by linawolf** [comment]
Solved by https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/1121
