### ISSUE TITLE
Add information about t3:id in XLIFF language files

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1094]
Add to page: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Internationalization/XliffFormat.html

----

t3:id is an (optional?) property in the .xlf files. A timestamp (current time) can be used. 

It is used to keep track of a file in case it is moved.

It _should_ be used in the core (I think) and a script to check for uniqueness exists  (`Build/Scripts/xlfcheck.sh`)?

-------

Questions: 

* should this be used in extensions as well?
* Is this still used? Is it used within the core? How so? Often the language files are referenced by path so how does this help? Or does it help to keep track of the connection between base file and translated file?

----

Information from [Slack](https://typo3.slack.com/archives/C028JEPJL/p1605199841071500):

* https://github.com/TYPO3/TYPO3.CMS/commit/391917c49302a56b0493425614bf7410be63c690

Concerns core development:

> You may rename a translation file but must not split it into multiple files since we use the unique id to track move and renaming of translation files.

> Every new language file must have a unique id (timestamp “now”) in the header that is not changed if the file is moved later on.

https://wiki.typo3.org/Development/Memos/TranslationHandling

check for uniqueness: 

* https://review.typo3.org/c/Packages/TYPO3.CMS/+/34184/

That file still exists in the core in `Build/Scripts/xlfcheck.sh`.

----

As always, for some of this information, it should be checked if it is still up to date.

**Comment by linawolf** [comment]
@sypets can you make a PR about that? There seems to be almost all information in your issue here...
