### ISSUE TITLE
Add naming conventions to custom site configuration page

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1112]
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/SiteHandling/ExtendingSiteConfig.html

There are currently no naming conventions for custom site configuruation.

---

Should get someone from core team to sign off on. 

---

Current proposal: use extension keys to namespace configuration (`tx_<extkey>`) as suggested by Xavier:

> Do we have naming conventions for custom site configuration? I think it might be a good idea to define this for custom configuration, so that there are no conflicts and each extension has its own namespace.

> when we extend a table, it was a best practice (even enforced by default in the good old days) to prefix the new field with `tx_<extkey>_`, this could be an idea

https://typo3.slack.com/archives/C03AM9R17/p1605783288046700

e.g. instead of this:

```
rootPageId: 1
base: https://example.com
myProject:
    recordStorage: 15
```

do this:

```
rootPageId: 1
base: https://example.com
custom:
  tx_cool_extension:
    recordStorage: 15
```

**Comment by sypets** [comment]
See also general page for naming conventions: https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ExtensionArchitecture/NamingConventions/Index.html

**Comment by DavidBruchmann** [comment]
I use usually the domain-name. Dots, scores or underscores could be replaced by each other but it's not related to an extension primarily.

**Comment by sypets** [comment]
I am thinking about extensions which might be made public and which add their own configuration to config.yaml and possibly even extend the GUI. This is currently possible - as documented.

**Comment by DavidBruchmann** [comment]
ohh sorry I missed the extending part for which the extension signature or -key is absolutely fine.

**Comment by dogawaf** [comment]
An example in the wild: https://github.com/TYPO3-Solr/ext-solr/blob/master/Configuration/SiteConfiguration/Overrides/sites.php

**Comment by linawolf** [comment]
@DavidBruchmann @dogawaf @sypets could one of you make a PR about this?

**Comment by linawolf** [comment]
No reaction within a month
