### ISSUE TITLE
Settings for $GLOBALS[‘TYPO3_CONF_VARS’] are not accessible via Online documentation

### ISSUE THREAD

**Issue by sbusemann** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1141]
As a user, I want to access the documentation for the system configuration via online documentation

See: https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ApiOverview/GlobalValues/Typo3ConfVars/Index.html

AC:
* Configuration Settings are described also in the online documentation

**Comment by sypets** [comment]
As user, I agree.

I also raised the issue before: #797.

I would like to close this as duplicate. Please upvote #797 and leave comment.
