### ISSUE TITLE
Add page "/Terms.html" (not in menu)

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1207]
## Proposal
I suggest to add a page /Terms.rst giving /Terms.html.

## Idea
It does not appear in the menu and will not bother users. It's meant for editors. You need to type "Terms.html" to open the page in the browser. Or you can click the entry "Terms and spellings" in the index.

## Demo
To show what I mean I've done it already:
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/Terms.html

The idea is to provide an easy way for editors to share what the spellings are that we agree on.

## Frontend
Nice looking, rather compact, simply reusing the "guilabel" design and textrole.
![image](https://user-images.githubusercontent.com/307057/102824727-b21cd700-43dd-11eb-9a29-a4fcad22e2f2.png)

## Backend
Easy to edit.

![image](https://user-images.githubusercontent.com/307057/102824784-cbbe1e80-43dd-11eb-8f08-3fb0b00892e6.png)

## Opinion
What do you think?

**Comment by linawolf** [comment]
I would prefere to have one point of truth. This information is not specific to TYPO3 Explained

**Comment by sypets** [comment]
Is the idea to have this file in each manual? I think this is rather a question for a style guide where we already have a list of terms. Maintaining this in every manual would be very tedious and there are bound to be duplicates.

Why create something new when we already have a list: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/Glossary.html

I like the format of the this new page though. It could be possible to replace the existing page in "Writing Documentation" with this.

**Comment by marble** [comment]
Fine. This was just a first step. I wanted to come up with a proposal and something working, so a local /Terms.rst was the best I could come up with considering the time. Meanwhile I reworked the existing https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/Glossary.html page and find it very usable. So yes, that's the place where the word lists should be compiled. If we can keep that central page we could and should remove the /Terms.rst page here. So that was just an intermediate step for the better solution.

**Comment by linawolf** [comment]
Ok so I go ahead and make a PR to remove it again.
