### ISSUE TITLE
ExtensionBuilder - only for 9.5

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1237]
There seems to be currently nor version for the extension_builder for versions greater 9.5 https://packagist.org/packages/friendsoftypo3/extension-builder 

Should we still use it as an example here: 
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/CreateNewExtension/Index.html

**Comment by remonator** [comment]
There is a branch [v10-compatibility](https://github.com/FriendsOfTYPO3/extension_builder/tree/v10-compatibility) but it has to be checked out explicitly... perhaps a note or similar admonition about that for release 10.4 would help?

**Comment by linawolf** [comment]
yes great, can you do that, @remonator ?

**Comment by remonator** [comment]
> 
> 
> yes great, can you do that, @remonator ?

Sure! I think it would be a patch for 10.4 only though, at least for now...

**Comment by remonator** [comment]
@linawolf you can close now as this probably won't be merged into `master`
