### ISSUE TITLE
Introduction looks outdated

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1238]
It is a very prominent page, however the screenshots are from TYPO3 7, the grafic is hard to read and understand and everything seems to be quite outdated. Please someone take mercy on this page...

https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/Introduction/Index.html

**Comment by flicstar** [comment]
Is it just this one page we need to work on? 
I can have a go at the text - we wrote something similar for the guidebook. I know we also got an updated diagram for the book, which is free for us to use. So I'll see if I can track that down to use here.
You could update the one screenshot too. 
If that's what you mean @linawolf Let me know if you had something else in mind.

**Comment by linawolf** [comment]
Yes @flicstar, that is exactly what I have in mind!!
