### ISSUE TITLE
Ajax chapter only for backend?

### ISSUE THREAD

**Issue by remonator** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1287]
This is rather a set of questions:

1. Am I right to assume that the chapter about Ajax is only valid for backend-related requests?

2. How is this done:
> To be able to send a request, the module TYPO3/CMS/Core/Ajax/AjaxRequest must be imported.

3. If this chapter is not about implementing a frontend-originating request, shouldn't that be explained too? I read a lot about defining a separate TypoScript `PAGE` object to handle this sort of requests, yet I haven't found anything in the docs so far.

Possibly related to #742

**Comment by linawolf** [comment]
@remonator could you provide a PR improving this chapter?

**Comment by remonator** [comment]
> 
> 
> @remonator could you provide a PR improving this chapter?

@linawolf I would but I'm afraid I don't follow what scenario the current docs describe exactly. I could, however, submit something about my 3rd item if sb. would proofread :-)
