### ISSUE TITLE
Best practice for cross-site-contents

### ISSUE THREAD

**Issue by typecat** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1323]
As an integrator,
I want to know the best practice to manage contents that are shared between multiple sites,
so that I have a clean and upgrade-save approach.

Example:
A multi-site TYPO3 setup, where each country has an own root page tree. All the country websites display contacts in different languages (English as default, country language as second). The contacts themselves do not belong to a specific country and should be translate-able, so that the editor does not have to enter contents that stay the same in each language (e.g. email address) multiple times, but merely change some contents through localization.

**Comment by medarob** [comment]
We have a multi domain and multi language instance. Variouse sites have either German news, French news, English news, Czech news or 2 of those.
Furthermore we have categories, Event records from ext:sf_event_mgt, contacts, powermail forms which are all localized.

We use those datasets across multiple websites.

Our approach as suggested by @fjacobi in the slack channel:
We created a new page called "dataset" and added a site config with German (base), English, French, Czech languages. The we moved all folders with the data described above 1:1 to this page. Then we changed the doktype from "page" to "folder".
So, now we have a **folder** "dataset" and all localization flags are available again.

Downside: "The siteconfig of this folder is now labeled as not needed anymore (in the site config module) and it can be deleted." Obviously you can't delete this site config. So, if this approach is necessary for working cross-site conent, maybe there needs to be a new "data folder"-doktype which can be used together with site configs but without this message in the site module?

We will test this setup.

**Comment by linawolf** [comment]
We cannot really cover everything in TYPO3 explained. There are multiple possibilities always depending on the concrete use case. In your use case I would probably store the contacts as records of an extension capable of translations.
