### ISSUE TITLE
Add naming conventions for upgrade wizard identifier

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1334]
**Suggestion:**

use 

**extensionKey_wizardIdentifierAsLowerCamelCase**

```
$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['ext/install']['update']['extensionKey_exampleUpgradeWizard']
   = \Vendor\ExtName\Updates\ExampleUpdateWizard::class;
```

Using lowerCamelCase instead of UpperCamelCases gets you all lowercase in the simplest of cases:

**extensionkey_wizardname**.

----

What you currently often see: 

1. simple identifers without extension names, e.g. in https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/UpdateWizards/Creation.html#registering-wizard
2. Fully qualified class names `\Vendor\ExtensionName\Upgrade\UpgradeWizard::class`

about 1:

Extensions can create upgrade wizards too but unfortunately all share the same namespace in `$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['ext/install']['update']`. 

If simple, arbitrary names are used as identifier (and thus as key in the array), several extensions could accidentally use the same identifier and effectively overwrite the other upgrade wizard registration.

That is why the extension name is prepended above.

about 2: 

That makes it more difficult to call the wizard on the command line as you have to supply full class name with namespaces and quote correctly.

**Comment by susannemoog** [comment]
The ::class one is the one easy to use as we have autocomplete, but as you said I would avoid using it as it makes it harder to call the wizard. I would propose `extkey_exampleUpgradeWizard`.

**Comment by sypets** [comment]
Yes, this is what initiated this issue: I had used a wizard of calendarize and then noticed that it used the fully qualified class name as identifer. This makes it difficult to call on the command line:

php vendor/bin/typo3 upgrade:run "\\HDNET\Calendarize\\Updates\\CalMigrationUpdate"

(You also have to figure out how to quote the backslashes in your shell, yuck).

So I created a PR: https://github.com/lochmueller/calendarize/pull/498/files

but then wondered what name should be used:

* calMigration (may not be unique across all extensions)
* calendarize_calMigration (is what got merged)

**Comment by sypets** [comment]
I updated the initial text. 

Suggestion is now **extensionName_wizardName** (both in lower camel case, which means you have an all lowercase in the simplest of case: **extkey_wizardname**) which is the same as your suggestion. @susannemoog

**Comment by bmack** [comment]
How does this look like with an extension key like `news_events`?

**Comment by sypets** [comment]
@bmack 

> How does this look like with an extension key like news_events?
newsEvents_wizardName

Open for suggestions ...

**Comment by lolli42** [comment]
Normally, I'd say we should stick to the class name as FQCN since it's unique.
However, I see the shenanigans with typing this on CLI forcing quoting for backslashes ... 
So i'd be fine with 'extension_key_lastPartOfClassName' or 'extensionKey_lastPartOfClassName' or similar.

**Comment by lolli42** [comment]
Note: we may not want to change this for existing wizards since (afaiks?) this key is also used in the registry to mark wizards as 'done'.

**Comment by bmack** [comment]
OK. Sounds good. Let's go with "newsEvents_wizardName" and once we document it, let us add some good and real examples so people directly know how to use it:

* container_upgradeColumnPositions
* newsEvents_migrateDateTimeFields
* bootstrapPackage_addNewDefaultTypes

Like this?

**Comment by mbrodala** [comment]
@lolli42 Also wizards can be referenced directly at least in the TYPO3 Console to run them separately:

https://docs.typo3.org/p/helhum/typo3-console/6.4/en-us/CommandReference/UpgradeRun.html

**Comment by sypets** [comment]
Will change docs on upgrade wizard page. 

I would also not change for existing wizards. Information about the wizard is stored in sys_registry using the identifier. (will add that to the docs).
