### ISSUE TITLE
FlexFormProcessor: We can remove custom class now

### ISSUE THREAD

**Issue by jonaseberle** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1338]
For v11+ we can remove the custom flexform dataProcessor here:

https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/blob/master/Documentation/ApiOverview/FlexForms/Index.rst#how-to-access-flexforms-from-fluid

We have it in Core now: https://review.typo3.org/c/Packages/TYPO3.CMS/+/62108

**Comment by susannemoog** [comment]
Should probably be replaced with a link / reference to https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/ContentObjects/Fluidtemplate/DataProcessing/FlexFormProcessor.html
