### ISSUE TITLE
use new api instead of global 

### ISSUE THREAD

**Issue by tmotyl** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1346]
The content of the page https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/BackendUserObject/Index.html
should be change to use the new context api
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Context/Index.html#user-aspect

**Comment by susannemoog** [comment]
@tmotyl how do you get all that info? The user aspect as far as I can see can deliver only the user name - all the other examples on that page cannot be done via the user aspect (yet) or did something change there?

**Comment by tmotyl** [comment]
Hmm, you're right. I've just saw GLOBALS and a alarm "use new api" was triggered in my head ;)
Lets then just add information/link about the new API, and add examples to isAdmin and getting username with the new API. What do you think?

**Comment by linawolf** [comment]
@tmotyl  feel free to open a PR
