### ISSUE TITLE
Reorganising testing chapters

### ISSUE THREAD

**Issue by alexander-nitsche** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1359]
The logic of the structure of the TYPO3 Testing chapters is:

- Testing
  - Core testing => how to run unit / functional / acceptance tests when developing the TYPO3 Core
  - Extension testing => how to run unit / functional / acceptance tests when developing a TYPO3 3rd-party extension
  - Project testing => how to run unit / functional / acceptance tests when developing a TYPO3 project
  - Writing unit tests => which built-in features does the `typo3/testing-framework` provide for unit tests
  - Writing functional tests => which built-in features does the `typo3/testing-framework` provide for functional tests
  - Writing acceptance tests => which built-in features does the `typo3/testing-framework` provide for acceptance tests

The headlines seem to suggest that the "Writing * tests" chapters show also how to run the tests on the command line which is not the case. Therefore the "Writing * tests" chapters contain a line about what this chapter is about and what not, but its place in the text seems to be not prominent enough. The chapters could do with a re-sharpening in pointing out what they are about and what not, and where to find the remainder to write _and_ run tests.

**Comment by sypets** [comment]
slightly related, please also see https://github.com/TYPO3-Documentation/tea/issues/241

**Comment by linawolf** [comment]
merged
