### ISSUE TITLE
How to create a section with typo3

### ISSUE THREAD

**Issue by elhadjyoussouf** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1417]
For more than a day, I've been wanting to set up a section block with an image, descriptive text and a button.
Unfortunately typo3 does not have this feature by default. How can I do this?

thank you for answering me!

**Comment by linawolf** [comment]
Have a look into the extension https://extensions.typo3.org/extension/introduction, it demonstrates using custom content elements. Or read here: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/ContentElements/AddingYourOwnContentElements.html

You can also try to find help on Slack. 

This issue tracker is for improving the documentation so I would close this issue. You can reopen it if you have ideas of how to improve the documentation on this.
