### ISSUE TITLE
Improve the extension publishing documentation

### ISSUE THREAD

**Issue by alexander-nitsche** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1420]
- [x] remove duplicate content in extensions.typo3.org and docs.typo3.org, see [gitlab issue](https://gitlab.typo3.org/services/t3o-sites/extensions.typo3.org/ter/-/issues/383) and [github PR](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/1419)
- [x] [PublishExtension article](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/blob/master/Documentation/ExtensionArchitecture/PublishExtension/Index.rst): Fix linking of "See Publish an Extension for more information .."
- [x] [PublishExtension article](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/blob/master/Documentation/ExtensionArchitecture/PublishExtension/Index.rst): Fix formatting, e.g. "An update of the extension .."
- [x] [PublishExtension article](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/blob/master/Documentation/ExtensionArchitecture/PublishExtension/Index.rst): Rename Packagist advantage to "Make extension available for installation in composer TYPO3 instances" and link composer to dedicate docs page
- [x] [PublishExtension article](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/blob/master/Documentation/ExtensionArchitecture/PublishExtension/Index.rst): Add TER advantage "Make extension available for installation in non-composer TYPO3 instances" and link non-composer to dedicate docs page
- [x] [PublishToTER article](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/blob/master/Documentation/ExtensionArchitecture/PublishExtension/PublishToTER/Index.rst): Replace "two possibilities" by "three possibilities"
- [x] [PublishToTER article](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/blob/master/Documentation/ExtensionArchitecture/PublishExtension/PublishToTER/Index.rst): <del>Add a minimal tailor CLI example</del> => reduce redundancy, link to good documentation and examples at Tailor's homepage instead
- [x] [PublishToTER article](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/blob/master/Documentation/ExtensionArchitecture/PublishExtension/PublishToTER/Index.rst): <del>Add a link to REST API, e.g. https://extensions.typo3.org/faq/rest-api/</del> => Tailor's homepage links it at the first line
- [x] [PublishToTER article](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/blob/master/Documentation/ExtensionArchitecture/PublishExtension/PublishToTER/Index.rst): Reduce linking to deprecated SOAP interface tools, to reduce importance of this list item

**Comment by alexander-nitsche** [comment]
The latest commits related to extension publishing have been backported to branches 10.4 and 9.5. These are

- [BUGFIX] Fix formatting for publish an extension (397244a4058392f821a29f53b1f43074b3fa437b)
- [TASK] avoid duplicate content on extensions.typo3.org and docs.typo3 (b8ea5233a4def9f1a52caecfd504dfe10882c020)
- [FEATURE] Add link to crowdin on publish page (4cf1b2085543857d97a11b83fca01477dd8a13b7)
- [TASK] Improve articles of extension publishing (c0f055db090bea8ab142bf7b5d59aecd5decd8bd)

@linawolf / @susannemoog / @sypets : Branch 8.7 does not provide a page about extension publishing yet. Should we add it there too? Are the requirements for publishing an extension in 8.7 the same as for newer TYPO3 LTS?

**Comment by sypets** [comment]
@alexander-nitsche I don't know about the tailor publishing but the rest should be the same. However, some cross-references might not be available in 8.7. Question is if you want to bother with post-LTS (ELTS) in general. In the past I think we usually backported the things to the LTS versions but not to older versions.

**Comment by susannemoog** [comment]
@alexander-nitsche the requirements would be the same, including Tailor. However, as Sybille said, usually we don't bother with versions older than the oldest supported LTS for the docs.

**Comment by alexander-nitsche** [comment]
Ok.
