### ISSUE TITLE
TYPO3 backend styleguide I - role of styleguide extension and where to document

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1437]
Originally, I opened this in EXT:styleguide (but I opened it as a [subtopic only addressing the icons](https://github.com/TYPO3/styleguide/issues/210)). I think it would still be better to add the missing things in EXT:styleguide but I am currently not sure.

Basically, I think there are several subtopics / questions:

1. role of styleguide extension: does it show the components in the backend or does it also give styleguide advice and define rules for when and how to use the components? Does it define styles for all components used in the backend (not just in FormEngine)
2. Should there additionally be a styleguide as Documentation or something automatically generated online? Advantage: can be perused with browser, can be linked to etc.
3. What is currently missing in styleguide? (e.g. style for icons in content element wizard, BE information in plugins)
4. Can the core API / framework be enhanced so that core provides some more functionality where extension authors currently write it from scratch (which automatically leads to inconsistency?). This is in my opinion the preferred solution (and less work for everyone long-term) - you don't need to define style for things which are already handled by the core. But the core currently often just has the role of a very low-level API where extension authors do the rest and I am not sure if this is even welcome. Anyway, this can be better handled in the core (e.g. as forge issues) - but it also affects the other questions!

Question is also, what is easier to maintain long-term, what will help to enforce consistent style in the core Backend and in extensions.

**Examples for 1:**

Does it show the features or does it also explain where and how to use them?

The current styleguide does do this, for example it advises to put the action icons in the last table row cell (column) in tables.

![image](https://user-images.githubusercontent.com/13206455/123919925-baa22b80-d985-11eb-88ec-c6780cec0290.png)

However, it does not do this in several other places. It does not say when and how to use Infobox or flashmessages, it does not say if and when to use Tabs in modules (and the core rather usually uses 
 a select to seperate functionality in modules), it does not define the style for icons in the content element wizard, it does not define the style for plugin information in the backend etc.

**about 2: Styleguide as Webpages**

I originally thought one could add Documentation to the styleguide and use automatically generated screenshots from the styleguide - this way you could have an online version of it. I don't think this is a good idea anymore. The pages are sometimes quite long so you have to scroll. So you have to split this up. Keeping this up to date would be a lot of work.

Is it possible to put the generated HTML pages online - with anchors for subheaders and the menu? Is that worth the effort? I see the main advantage that you could link to it. And the information would be less hidden. If the styleguide is used more as styleguide - not everyone will install it and see the information.

**about 3: Examples for what is missing**

1. images in content element wizard, see https://github.com/TYPO3/styleguide/issues/210
2. showing information for plugins in the backend - extension authors are free how they do this, any HTML can be inserted and another disadvantage is you have to write a lot of code from scratch just to show the information from the plugin.

Examples, see news + calendarize (which look quite differently):

news:

![image](https://user-images.githubusercontent.com/13206455/123914525-c7bc1c00-d97f-11eb-99ac-c803239cce44.png)

calendarize:

![image](https://user-images.githubusercontent.com/13206455/123916441-f0ddac00-d981-11eb-8f9b-6b58ac3f1354.png)

**About 4: core API**

Example is number 2 from previous point: showing information in plugins. This currently requires a lot of code to be written from scratch and is not documented (AFAIK).

see news (all this is required to show the information in the backend for the plugin):

* https://github.com/georgringer/news/blob/master/Classes/Hooks/PageLayoutView.php
* https://github.com/georgringer/news/blob/master/Classes/Utility/TemplateLayout.php

IMHO news handles this great and this should be integrated into the core in some way.

**Comment by linawolf** [comment]
We do have some basic info here: https://docs.typo3.org/m/typo3/reference-tca/main/en-us/Examples/StyleGuide.html

Your feature request was merged

I would say the complete issue doesn't belong to TYPO3 explained...
