### ISSUE TITLE
Wrong docs for LinkHandler

### ISSUE THREAD

**Issue by helsner** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1491]
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/LinkBrowser/Linkhandler/CustomLinkHandlers.html

Those docs seem outdated to me.
At least the mentioned method of adding a custom link/type does not work in my case
I guess whats missing is a hint about this here:

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.7.x/Important-79647-AddedHookForResolvingCustomLinkTypes.html

Although i'm not sure, as it is not working right now for me

**Comment by linawolf** [comment]
We are currently revising the chapter. We added a brand new tutorial which might help you. The events that have been introduced with TYPO3 v12 are documented. Hooks have usually never been documented as they had no clean API.
