### ISSUE TITLE
Add documentation for Signal/Slot

### ISSUE THREAD

**Issue by ghost** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#15]
There is a chapter about Hooks: http://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Hooks/Index.html

There should also be a chapter about Signal/Slot.

It would be helpful to show when to use Hooks and when Signals should be used - in TYPO3 CMS extensions and TYPO3 CMS core.

**Comment by DavidBruchmann** [comment]
Mhm, is AOP integrated now in TYPO3 or extbase?
Or is the signal/slot-feature in TYPO3 integrated without AOP?

**Comment by sypets** [comment]
Can you please check if [this section on Hooks and Signals](https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Hooks/Concept/Index.html#hooks-and-signals-vs-xclass-extensions) is sufficient and if not: enhance it?

P.S. Would be great, if we could work through these old issues and get them solved

**Comment by sypets** [comment]
There is a forge issue for this: https://forge.typo3.org/issues/59089

I will add some information from the forge issue to this issue:

_"Resources:
* https://usetypo3.com/signals-and-hooks-in-typo3.html
* http://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartIII/SignalsAndSlots.html#signals-and-slots

The place to put the documentation should be: https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Hooks/Index.html in my opinion.
The signal is already documented as a concept at: https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Hooks/Concept/Index.html#using-signals .

The documentation, in my opinion, should cover:
- What's the difference between hook and signal
- As Extension developer, when should I use hooks or signals?
- As Integrator / Developer, how can I connect to a signal (already part of documentation)"_

**Comment by sypets** [comment]
This issue is marked as postponed because Hooks / Signals will be overhauled completely in Core.

**Comment by DanielSiepmann** [comment]
I'll add a cross reference to the existing https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Hooks/Index.html#hooks .

**Comment by sypets** [comment]
This is now done: Both Signals / Slots and Events have been documented a while ago.
