### ISSUE TITLE
Foldername for .tsconfig?

### ISSUE THREAD

**Issue by peerlight** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1521]
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/CodingGuidelines/CglTsConfig.html says 
"Page TSconfig files are located in the directory extension/Configuration/**TsConfig**/Page ..."

https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/FilesAndLocations/Index.html says
"Configuration/**TSconfig**/Page
    page TSconfig, see chapter ‘page TSconfig’ in the TSconfig Reference. Files should have the file extension .tsconfig.
Configuration/**TSconfig**/User
    User TSconfig, see chapter ‘user TSconfig’ in the TSconfig Reference. Files should have the file extension .tsconfig. "

So what is correct: `/TSconfig/` or `/TsConfig/`?

**Comment by mbrodala** [comment]
The 1st variant should be preferred AFAIK. See the results of the question **IF using folder structures for TSconfig, what should be the default folder names?** here:

https://decisions.typo3.org/t/file-endings-for-typoscript-and-tsconfig-files-results/71

Also TYPO3 itself uses this casing:

https://github.com/TYPO3/typo3/tree/c78469c016b0ebe515fbf9f7d717e575da2652e0/typo3/sysext/backend/Configuration/TsConfig

The exact casing was not clarified explicitly though, so if you really care about this, you could start a new decision process.

**Comment by peerlight** [comment]
Thanks, just stumbled upon this inconsistency

So https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/FilesAndLocations/Index.html was misleading and could be updated to "Configuration/TsConfig/..."
