### ISSUE TITLE
Add information how to reset query parts

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1526]
>  Be aware to clone your object or resetting the query parts to prevent side effects in case of multiple usages.

https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/DependencyInjection/Index.html#arguments

It is mentioned to reset the query parts but not how to do that. Perhaps adding this information or a link to the information might be helpful. (Actually, I think it might be "cleaner" to add that information to the QueryBuilder page and link to it from the DI page to not clutter up the DI page with too much information about QueryBuilder).

probably

`$queryBuilder->resetQueryParts();`

or only reset the query parts which should be reset.

Not sure what is recommended (clone or resetQueryParts), I guess it also depends on the context.

Related:

* https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/1525

**Comment by linawolf** [comment]
With https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/1637 queries cannot be reused in the old way anyway...

**Comment by brotkrueml** [comment]
The section was reworked some days ago, the query builder was a bad example to inject directly in the constructor via DI, now the connection pool is used.

Also the database chapter was reworked, so every example uses now the connection pool from which a fresh and clean query builder can be retrieved. So no need to reset the parts.
See: https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/Database/QueryBuilder/Index.html#instantiation

I close this issue. If you think something is missing, feel free to reopen it or create an new issue.
