### ISSUE TITLE
Invalid info https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/commit/a3e82245ac97d721c83cae2375417a3061073394

### ISSUE THREAD

**Issue by lolli42** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1529]
"ignore-as-root": false,

should not be used.

**Comment by jonaseberle** [comment]
Correct. It was only valid between https://review.typo3.org/c/Packages/TYPO3.CMS/+/69174 and https://review.typo3.org/c/Packages/TYPO3.CMS/+/71029
