### ISSUE TITLE
Link missing in master due to missing link target (in "Getting Started Tutorial"): Access Control Options

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1544]
> is described in the "Getting started tutorial"

![image](https://user-images.githubusercontent.com/13206455/136686739-67d2b7ed-dc9d-4854-8046-81c3d20c48ab.png)

In 10.4 this is a link, in "master", it is not.

* master: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/AccessControl/AccessControlOptions/Index.html#access-lists
* 10.4: https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ApiOverview/AccessControl/AccessControlOptions/Index.html#access-lists

----

The link is to `t3start:setting-up-user-permissions`. This no longer exists in the "Getting Started Tutorial" in "master".

----

I searched for the content that used to be on the page "[Setting up user permssions](https://docs.typo3.org/m/typo3/tutorial-getting-started/10.4/en-us/UserManagement/GroupPermissions/Index.html#setting-up-user-permissions)"  (in Getting Started Tutorial), but I don't know if it still exists.

**Comment by sypets** [comment]
Also, there are a number of other warnings for master: 

* master: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/_buildinfo/warnings.txt
* 10.4: https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/_buildinfo/warnings.txt

**Comment by tomwarwick** [comment]
Just a quick update on this.

The content that was removed from the new Getting Started Guide will be added / merged with the chapter in Core API > Backend access control. Once merged I will then fix the broken links.

**Comment by susannemoog** [comment]
The content has been re-added and the link has been fixed.
