### ISSUE TITLE
ext_emconf.php is outed for composer based installations

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1566]
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/blob/11.5/Documentation/ExtensionArchitecture/DeclarationFile/Index.rst is outdated, see https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.4/Feature-94996-ConsiderAllComposerInstalledExtensionsAsActive.html

but wait until https://review.typo3.org/c/Packages/TYPO3.CMS/+/71805 is merged to have some crosslinks

**Comment by linawolf** [comment]
This is handled in https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1449
