### ISSUE TITLE
Old Text with new example for namespaces

### ISSUE THREAD

**Issue by pitscribble** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#157]
In https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Namespaces/Index.html#creating-instances the text still speaks of escaping the backslashes, but since the 6.2 documentation the example shows the new syntax introduced with PHP 5.5 without quotes and without escaping and with added ::class. This is rather confusing. ;)
And imo in the new syntax shown in the example you do not omit the leading backslash, because it uses the  Fully qualified name of the namespace.

**Comment by marble** [comment]
Who can make the text and the example(s) congruent?
