### ISSUE TITLE
Resources in form-elements

### ISSUE THREAD

**Issue by DavidBruchmann** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#169]
In [CoreApiReference](https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/FormEngine/Rendering/Index.html) is written: 

> This is the second step of the processing chain: The rendering part gets the data array prepared by FormDataCompiler and creates a result array containing HTML, CSS and JavaScript. This is then post-processed by a controller to feed it to the PageRenderer or to create an ajax response.

Passing Resources like  CSS and JavaScript to form-elements is not clear and I get the impression I've to pass them by myself to pageRenderer.
Actually I'm creating a UserElement (userdefined, not related to users) and I don't see any option to pass there anything but HTML to the upper node.

**Comment by DavidBruchmann** [comment]
Even it's not yet absolutely clear how the params are getting passed to pageRenderer I see now how it's working also with UserElement.

**Comment by marble** [comment]
If you learned something - try to think about how you would update the text. And you could make a pull request!

**Comment by DavidBruchmann** [comment]
Yeah maybe I will pass another example including resources when I'm done with my case.
