### ISSUE TITLE
Chapter about FormEngine missing in 7.6

### ISSUE THREAD

**Issue by DavidBruchmann** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#170]
Is there a reason that the chapter about [FormEngine](https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/FormEngine/Index.html) is missing in 7.6?

**Comment by marble** [comment]
Is this what you are looking for? https://docs.typo3.org/typo3cms/extensions/form/7.6/

**Comment by DavidBruchmann** [comment]
No, because the page I linked is explaining the hierarchy and the new kind of creating forms a bit deeper, so I think the whole chapter could just be backported to 7.6 too.
There is no doubt that some of the info can be collected somehow in the doc for 7 too, but it's another viewpoint and some info missing too.

I saw that the whole form-chapter of 7 (and probably more) was outsourced in another document for version 8, so comparison is a bit hard 1:1.
Nevertheless in the page I linked it's mentioned the new FormEngine was introduced in Version 7 but this docu is only available then in 8, that's not logical for me.

**Comment by DavidBruchmann** [comment]
Sorry, remarked you posted the Form-document for 7 already too, thought first it still would be api, but like I said, the chapter in the api-doc is missing and could be in 7 too.

**Comment by liayn** [comment]
@lolli42 knows a bit more about this maybe.

**Comment by lolli42** [comment]
The FormEngine docs have been written for version 8 of core - there are various parts that don't apply to v7 this way, thus I did not backport this. I'll personally not spend the time to review the v8 version in details to extract a v7 version from it.

**Comment by lolli42** [comment]
I'd close this issue. If anyone likes to step to create a v7 version, feel free to contact me for some pointers.
