### ISSUE TITLE
Please remove branch sypets-transport_smtp_encrypt

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1821]
branch https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/tree/sypets-transport_smtp_encrypt can be removed. I do not have write access. Thanks.

**Comment by linawolf** [comment]
Done. Is something wrong with your user rights? Please get in touch on slack
