### ISSUE TITLE
Missing images on page Signals / Slots 10.4?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1926]
![image](https://user-images.githubusercontent.com/13206455/176232724-407cd31a-23f8-4255-a6b9-167d1b81e845.png)

https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/Events/SignalsSlots/Index.html

**Comment by linawolf** [comment]
Solved by commit
