### ISSUE TITLE
Fix 404 for backend modules?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1998]
When searching for things via e.g. Google, some results are returned which are no longer available.

Perhaps some redirects can be created:

1. search for: typo3 configure default backend module
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/HowTo/BackendModule/BackendModulesWithoutExtbase/BackendModuleApiWithoutExtbase.html

should be
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/HowTo/BackendModule/CreateModule.html

**Comment by linawolf** [comment]
Created the redirect
