### ISSUE TITLE
Explain role of table sys_language for site and language handling

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#2022]
In the site configuration "Add language" the role of the `sys_language` table is not explained - at least I did not find it.

https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/SiteHandling/AddLanguages.html

Nowadays, the languages are configured in the site configuration, but the sys_language records still exist.

Questions:

* do you still need to add the language in the sys_langage table?
* why?
* what takes precedence where, e.g. in site configuration and sys_language table some configuration is configured (e.g.  "flag")
* do you need to configure the default language?

In a standard installation with introduction package, sys_language contains a record for each language used for translations, but not for the default language:

page 0

![image](https://user-images.githubusercontent.com/13206455/182135402-91043176-eecd-4cf5-be16-5db3c3ed50ad.png)

Database (Created with introduction package, v11)

```
select uid,title,flag,language_isocode,nav_title,locale,hreflang,direction from sys_language order by uid;
+-----+--------+------+------------------+-----------+--------+----------+-----------+
| uid | title  | flag | language_isocode | nav_title | locale | hreflang | direction |
+-----+--------+------+------------------+-----------+--------+----------+-----------+
|   1 | Dansk  | dk   | da               |           |        |          |           |
|   2 | German | de   | de               |           |        |          |           |
+-----+--------+------+------------------+-----------+--------+----------+-----------+

```

**Comment by brotkrueml** [comment]
Table `sys_language` was deprecated in TYPO3 v11.3:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.3/Deprecation-94165-SysLanguageDatabaseTable.html

and removed in v12.0:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96107-DeprecatedFunctionalityRemoved.html

So, no need to document this anymore?

**Comment by sypets** [comment]
yes, that makes sense. What got me confused was that the entries are created in the "Introduction Package". However, if this is removed in v12, this shouldn't be a problem. Closing.

**Comment by sypets** [comment]
Checked in introduction package, created issue https://github.com/FriendsOfTYPO3/introduction/issues/83 (lasted main does not support v12 yet, though).
