### ISSUE TITLE
Document JS cgl

### ISSUE THREAD

**Issue by Chrissitopher** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#218]
_From @tmotyl on November 4, 2017 0:4_

TYPO3 Core team has decided to follow Airbnb CGL rules for JS files.
https://decisions.typo3.org/t/results-define-coding-guidelines-for-javascript/301

In this document we should at last:
- refer to airbnb rule set
- highlight few most important like:
-- 2 spaces indentation (no TABS)
-- single quotes should be used
--  jQuery variable should start with $
-- space between function keyword and opening bracket like `function () {`

_Copied from original issue: TYPO3-Documentation/TYPO3CMS-Reference-CodingGuidelines#15_

**Comment by Chrissitopher** [comment]
_From @liayn on November 4, 2017 8:45_

Please be cautious about the distinction between brackets, parentheses and braces in US English. I would in this case use parentheses or emphasize “round brackets“.

**Comment by Chrissitopher** [comment]
_From @tmotyl on November 4, 2017 17:46_

@liayn thanks for pointing it out. Until now I used  "parentheses" "brackets" as synonyms, but you're totally right that they mean different things.

**Comment by sypets** [comment]
In PhpStorm you can import a **.eslintrc** file, there is one for the Airbnb code style, see:

- https://github.com/airbnb/javascript/issues/1164
- https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base

If this works, it might be nice to point it out in the docs as well.

**Comment by sypets** [comment]
There is also an issue on forge about this: https://forge.typo3.org/issues/55579

**Comment by sypets** [comment]
Some very brief notes for other file types have been added to the Introduction of CGL section. See PR #249

I would suggest to close this issue unless someone wants to extend this.
