### ISSUE TITLE
Add information on the order in which TS is parsed

### ISSUE THREAD

**Issue by Chrissitopher** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#219]
_From @Chrissitopher on December 7, 2015 21:48_

What I personally am still missing is the rules after which _TSconfig_ overwrites other TSconfig:
- TSconfig of different groups and their order
- TSconfig of groups and of a user

The same can also be explained for _TS Templates_.

_Copied from original issue: TYPO3-Documentation/TYPO3CMS-Reference-TyposcriptSyntax#3_

**Comment by lolli42** [comment]
I think ts config reference outlines most load order details now: https://docs.typo3.org/typo3cms/TSconfigReference/UsingSetting/Index.html
