### ISSUE TITLE
Refine documentation about File Storages

### ISSUE THREAD

**Issue by ohader** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#2243]
Concerns: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Fal/Administration/Storages.html

The security team received a report about the behavior of file storages at https://huntr.dev/bounties/b052480a-56ac-4787-ba30-c4887b02b699/. I have to admit, that the current documentation is misleading here.

Please consider refining the description and possible add a reference to [3rd party packages](https://packagist.org/?query=secure%20download&type=typo3-cms-extension) dealing with authorization and file restrictions.

**Comment by linawolf** [comment]
@ohader could someone from the security team write a draft?

**Comment by ohader** [comment]
> @ohader could someone from the security team write a draft?

Busy with other topics... The concerns and misleading statements are shown quite well in the linked report at huntr.dev.
