### ISSUE TITLE
$GLOBALS[TBE_STYLES] is listed but contains no further information or links

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#2312]
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Configuration/GlobalVariables.html

* `stylesheetDirectories` is currently not documented at all, see https://stackoverflow.com/questions/53633454/adding-own-css-to-typo3-backend-v9

**Comment by brotkrueml** [comment]
It seems TBE_STYLES is only used for setting the stylesheet in backend (TYPO3 v12):

![image](https://user-images.githubusercontent.com/2566282/197174770-d08c24eb-f6c3-46db-93ff-e80e6d6d5e51.png)

**Comment by brotkrueml** [comment]
And this is the intro:

```
$TBE_STYLES configures backend styles and colors; Basically this contains
all the values that can be used to create new skins for TYPO3.
For information about making skins to TYPO3 you should consult the
documentation found at https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Configuration/GlobalVariables.html#confval-TBE_STYLES
```
https://github.com/TYPO3/typo3/blob/main/typo3/sysext/core/ext_tables.php#L7-L13

Funny: The link given hints to the documentation which does nothing say about how to skin.

**Comment by sypets** [comment]
@brotkrueml Thank you for following up. 

Yes,` $GLOBALS['TBE_STYLES']['stylesheet']` can be used to set styles in the backend (and only the backend, I think)

Some more notes:

There used to be a "skinning" reference. I never really looked in it, but might be useful to see what used to be documented. It might not be up to date though.

* https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Skinning

> TYPO3 v4.4 introduces a new skinning API which enables you to load as many stylesheets as needed in the Backend.

At one point it was migrated:

> This document has been merged into TYPO3 Explained since Core version 6.

You can still see the old content here: https://docs.typo3.org/m/typo3/reference-skinning/4.5/en-us/

For example: https://docs.typo3.org/m/typo3/reference-skinning/4.5/en-us/BackendCssApi/SkinningApi/Index.html#skinning-api

I did a grep in the TYPO3 Explained `TYPO3CMS-Reference-CoreApi` repo

`grep -r stylesheetDirectories Documentation`

No results. Might have been "optimized" away.

**Comment by brotkrueml** [comment]
In TER, only two serious extensions are providing a custom backend skin for a current version: "skins" and "aimeos_t3skin"
https://extensions.typo3.org/?L=0&id=1&tx_solr%5Bq%5D=skin

This may be a starting point to look what can be done and how it is done.

**Comment by brotkrueml** [comment]
TBE_STYLES is finally deprecated:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.3/Deprecation-100033-TBE_STYLESStylesheetAndStylesheet2.html

There is a new setting in TYPO3_CONF_VARS which can be used to add custom CSS files to the backend.

So, I assume, this issue can be closed?

**Comment by sypets** [comment]
ok
