### ISSUE TITLE
Add documentation for writing Upgrade Wizards

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#233]
Most of the stuff todo is probably self-explaining (inherit from AbstractUpdate, add functions checkForUpdate,  performUpdate etc.

It might be useful to provide
* some general guidelines. 
* Naming conventions? (some are named *Update, some *UpdateWizard ...)
* can one assume that the DB compare has already been run, why does ExtensionManagerTables do the schema migration (in getUpdateStatements).

**Comment by sypets** [comment]
There is still a decision pending so this should be postponed.

**Comment by DanielSiepmann** [comment]
I would also like to have this chapter. In my point of view this wizards would make TYPO3 updates much easier. We should help developers to provide them. This would solve one of the biggest issues TYPO3 does have right now.

But we should discuss the chapter in more detail, perhaps we should make a short call on slack?

**Comment by sypets** [comment]
Actually, the pending change is kind of on my todo list. But it only concerns whether the SQL statements should be displayed at all, or output in log output or not at all. This _might_ concern the function parameters for the update function. Apart from that, we could start on this chapter and enhance it for future changes.

**Comment by sypets** [comment]
Is addressed by pending pull request so will close this now.

**Comment by sypets** [comment]
@DanielSiepmann About the new chapter https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/UpdateWizards/Index.html

If the Core API is rather for using TYPO3 Core API and not developing within the core, isn't performing update tasks within `class.ext_update.php` the preferred method for extensions?

**Comment by sypets** [comment]
Ok, I now learned that class.ext_update.php is no longer the preferred method. Sorry about that.

**Comment by DanielSiepmann** [comment]
We should mention the state of `class.ext_update.php` in the docs to make the docs complete and let everyone know that this possibility exists and works and why it should no longer be used.

Where did you get the info that this is no longer preferred?

**Comment by DanielSiepmann** [comment]
@lolli42 @mbrodala can you tell us the state of `class.ext_update.php` so we can update the docs accordingly? Is it still supported, are there plans to remove it and what is the main difference to update wizards?

**Comment by mbrodala** [comment]
Yes, it is still supported, I am not aware of plans to drop it anytime soon.

`ext_update` classes require you to do everything yourself starting from checks, whether your script should run at all and doing output.

Compared to that the update wizards provide a light framework for this and are cleanly integrated with the TYPO3 Install Tool / maintenance area. You don't need to take care of setting some flag or similar to prevent updates from being executed twice. And thanks to the TYPO3 Console you can execute update wizards via CLI too which is impossible with `ext_update`.

**Comment by sypets** [comment]
@DanielSiepmann Can we close this or are you still working on it? In my opinion, current chapter is more than sufficient.

**Comment by DanielSiepmann** [comment]
I've to add a note about the `class.ext_update.php` file for completeness. I will not explain it in deep, just mention it so everyone knows what it is about, if he will see this file.

**Comment by DanielSiepmann** [comment]
This issue should be auto closed if the open pull request got merged.
