### ISSUE TITLE
Example "Adding elements to the Content Element Wizard" doesn't works anymore

### ISSUE THREAD

**Issue by MarkusGehrig** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#234]
The code block on following page, which shows a example of the integration has a mistake.

https://docs.typo3.org/typo3cms/CoreApiReference/8.7/ApiOverview/Examples/ContentElementWizard/Index.html

The array identifier "icon" was dropped and doesn't work anymore. You have now to use the the array identifier "iconIdentifier" and the Icon-API.

**Comment by sypets** [comment]
Thanks for your report, Markus. Do you want to make the change yourself?

**Comment by sypets** [comment]
I don't know if you have contributed to the docs yet, so I am adding some information:

You can use the "Edit me on Github" button on the top right of the page. 

Also, you might want to check out this video: https://www.youtube.com/watch?v=wNxO-aXY5Yw
