### ISSUE TITLE
Lack of Extbase Validation Examples

### ISSUE THREAD

**Issue by ohader** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#2374]
### 1) https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/Extbase/Reference/Annotations.html#validate

→ seems like the mentioned `Validate` annotation was removed from the example

<img width="853" alt="Screen Shot 2022-10-31 at 17 19 52" src="https://user-images.githubusercontent.com/402145/199057641-1ebdee44-f0fe-4727-8281-2c36423a225b.png">

### 2) https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/Extbase/Reference/Validation.html#validation-of-model-properties

→ seems like the mentioned `StringLengthValidator` was removed from the example

<img width="858" alt="Screen Shot 2022-10-31 at 17 20 40" src="https://user-images.githubusercontent.com/402145/199057666-8cb5f48c-b694-4019-b5ce-6b390108c616.png">

Probably introduced with https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/commit/9c3866bc17eadda8205fee3dbe1a944eaebc5b39#diff-442aaaccdffc313e9f4f57c7111f4996e1c3beaf2fef107b72ab64efc4057ee4

**Comment by linawolf** [comment]
This is related to https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/11 

The code-snippet tool cannot use the new PHP Langauge Feature yet and just dismisses it as comment
