### ISSUE TITLE
Add documentation for LoggerAwareTrait to Info about logging api

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#239]
This info [Feature: #82441 - Inject logger when creating objects](https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.0/Feature-82441-InjectLoggerWhenCreatingObjects.html?highlight=loggerawaretrait) should be referenced in the [Logging API chapter.](https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Logging/Quickstart/Index.html)

**Comment by sypets** [comment]
Done: In Quickstart.

Also check other sections: https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Logging/Index.html

**Comment by sypets** [comment]
The change has disappeared. Needs to be researched and then cherry-picked if necessary.

**Comment by marble** [comment]
It's probably because I got it wrong and resolved the merge conflict the wrong way.

**Comment by sypets** [comment]
Ok, don't worry about it. I'll redo it.
