### ISSUE TITLE
Add information about other options for template configuration e.g. for using FluidEmail / add info about TemplatePaths

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#2441]
**Update: TemplatePaths is marked as internal**

-----

In the current configuration, it is recommended to override the templates in AdditionalConfiguration.php or LocalConfiguration.php

> If you want to provide custom templates or layouts, set this in your LocalConfiguration.php / AdditionalConfiguration.php file:

> typo3conf/AdditionalConfiguration.php
 $GLOBALS['TYPO3_CONF_VARS']['MAIL']['templateRootPaths'][700] = 
> 'EXT:my_site_extension/Resources/Private/Templates/Email';
 $GLOBALS['TYPO3_CONF_VARS']['MAIL']['layoutRootPaths'][700] = 'EXT:my_site_extension/Resources/Private/Layouts';

https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/Mail/Index.html#fluid-paths

As far as I can see, that is the only method given for adding / overriding the template, layout etc. paths.

However, often FluidEmail will be used in an extension and the templates supplied with an extension. In that case it would be good if the template was already configured in this extension (because otherwise you always have to set it up manually, which is unnecessary hassle).

In EXT:linkvalidator in TYPO3 v11 and v12 (main) in the core **TemplatePaths** is used. 

Perhaps we can look into that and add that to the docs. (It might also be a good idea to add that to the general Fluid section).

linkvalidator snippet v12:

```
$templateConfiguration = array_replace_recursive(
            $GLOBALS['TYPO3_CONF_VARS']['MAIL'],
            ['templateRootPaths' => [20 => 'EXT:linkvalidator/Resources/Private/Templates/Email/']]
        );

        // must be sorted after adding the default path to ensure already registered custom paths are called first
        ksort($templateConfiguration['templateRootPaths']);
        $templatePaths = GeneralUtility::makeInstance(TemplatePaths::class, $templateConfiguration);

        if ($this->emailTemplateName === '' || !$this->templateFilesExist($templatePaths->getTemplateRootPaths())) {
            // Add default template name to task if empty or given template name does not exist
            $this->emailTemplateName = 'ValidatorTask';
            $this->taskNeedsUpdate = true;
            $this->logger->notice($this->getLanguageService()->sL($this->languageFile . ':tasks.notice.useDefaultTemplate'));
        }

        $fluidEmail = GeneralUtility::makeInstance(FluidEmail::class, $templatePaths);
        $fluidEmail->setTemplate($this->emailTemplateName);
```

**Comment by sypets** [comment]
Beware there are 2 classes with the same name where the TYPO3 TemplatePaths extends the TYPO3FLUID one:

```
./typo3/sysext/fluid/Classes/View/TemplatePaths.php
./vendor/typo3fluid/fluid/src/View/TemplatePaths.php

```

see

* review https://review.typo3.org/c/Packages/TYPO3.CMS/+/42425/132/typo3/sysext/core/Documentation/Changelog/master/Feature-69863-UseNewStandaloneFluidAsComposerDependency.rst
* changelog: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/8.0/Feature-69863-UseNewStandaloneFluidAsComposerDependency.html
* git blame for the file (to see changes): https://github.com/TYPO3/typo3/blame/main/typo3/sysext/fluid/Classes/View/TemplatePaths.php

**Comment by brotkrueml** [comment]
TemplatePaths class is set to internal, so we should avoid it to suggest it in the docs:
https://github.com/TYPO3/typo3/blob/main/typo3/sysext/fluid/Classes/View/TemplatePaths.php#L27-L35

Also, this solution might be good for a system extension, but when we recommend something like that to users we should provide a method to do this easily with a Core function.

**Comment by sypets** [comment]
@brotkrueml ah, sorry, did not realize it was internal. In that case, this should probably be closed. Feel free to open if there is an alternative solution.
