### ISSUE TITLE
Document how to reliably handle $GLOBALS['LANG']

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#2462]
**Update**: _this post was updated, to add missing information or clarification_

The resource https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/HowTo/Localization/Php.html#localization-in-backend-context mentions that the array is only available in FE with available logged in BE user, but does not mention cli and install tool where the array is not instantiated in the backend context if Install Tool modules are used (e.g. Upgrade wizard).

Basically, it is always available if a BE user has been initialized. However, in the install tool context (whether logged in BE or not), it is not initialized.

---

When is `$GLOBALS['LANG'] initialized:
`
* in the frontend: only available with a logged-in backend user
* in the backend: always
* in cli: it depends if a backend user is available: one has to initialize it in the command with:  `TYPO3\CMS\Core\Core\Bootstrap::initializeBackendUser()`
* In install tool: no
*  In backend in install tool modules: no (same as install tool) probably not, see https://forge.typo3.org/issues/98992

## Resources

----

docs:

> getLanguageService() is a call to a helper method that accesses $GLOBALS['LANG']. In the Backend, the bootstrap parks an initialized instance of \TYPO3\CMS\Core\Localization\LanguageService at this place. This may change in the future, but for now the LanguageService can be reliably fetched from this global.

https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Localization/XliffApi.html

---

core LanguageService class

>  Usually this is injected into $GLOBALS['LANG'] when in backend or CLI context, and
> populated by the current backend user. **Don't rely on $GLOBAL['LANG'] in frontend, as it is only available in certain circumstances!**
> In Frontend, this is also used to translate "labels", see TypoScriptFrontendController->sL()
> for that.

https://github.com/TYPO3/typo3/blob/main/typo3/sysext/core/Classes/Localization/LanguageService.php

## Related

* core issue: https://forge.typo3.org/issues/98992
* Related docs issue: #2737
* docs: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/HowTo/Localization/Php.html#localization-in-plain-php

**Comment by brotkrueml** [comment]
In FE the $GLOBALS['LANG'] variable is only available with a logged-in backend user.

Lina added a page about localization some weeks ago: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/HowTo/Localization/Php.html

And you can always use the LanguageServiceFactory when `GLOBALS['LANG']` i not available.

In CLI context I assume it depends if a backend user is available: one has to initialize it in the command: `\TYPO3\CMS\Core\Core\Bootstrap::initializeBackendUser()`
