### ISSUE TITLE
IconAPI : add information how to get list of icons the core supplies

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#259]
Documentation of icon API looks up to date:
https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Icon/Index.html

I was missing the following information:
* where do I find a list of icons provided by the core
* are the icons supported as public API (e.g. actions-open). 

Here is a very useful and extensive Resource. 

https://usetypo3.com/icon-api.html

**Comment by lolli42** [comment]
the icons can be surfed using ext:styleguide from https://github.com/TYPO3/styleguide. i guess a screenshot of this section from styleguide would be great.
