### ISSUE TITLE
JavaScript in TYPO3 could use an example

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#262]
JavaScript in TYPO3 and Developing with Ajax in the TYPO3 Backend could use more content:

* Developing with AJAX in the TYPO3 Backend is empty: https://docs.typo3.org/typo3cms/CoreApiReference/latest/ApiOverview/JavaScript/Ajax/Backend/Index.html
* The entire section could use an example

**Comment by xw-alexander-nitsche** [comment]
Hello, i am in need of this section as well. Precisely i am looking for a way to implement proper AJAX handling in the frontend sending requests to Extbase controllers. If someone could point me to the way it is meant to be implemented, i would happily try to compose a draft of a documentation with examples after having it implemented and tested successfully.

**Comment by sypets** [comment]
@xw-alexander-nitsche great! Hope someone will pitch in. I would help, but this is not an area I feel I am knowledgable enough in. If you are on your own, maybe try the following:

* ask a well defined **specific** question about what you want to do on [StackOverflow](https://stackoverflow.com/) (use tag `[typo3]`) or #typo3-cms on [Slack](https://typo3.slack.com) ([register for Slack](https://my.typo3.org/index.php?id=35) first)
* see https://docs.typo3.org/typo3cms/InsideTypo3Reference/8.7/CoreArchitecture/Backend/Routing/Index.html It seems this chapter "disappeared" when "Inside TYPO3" was moved to "TYPO3 explained". Disclaimer: I don't know how outdated this is, but that is something you could ask on StackOverflow or Slack. Configuration/Backend/AjaxRoutes.php is used excessively in the core:

```
ls -1 typo3/sysext/*/Configuration/Backend/AjaxRoutes.php
typo3/sysext/adminpanel/Configuration/Backend/AjaxRoutes.php
typo3/sysext/backend/Configuration/Backend/AjaxRoutes.php
typo3/sysext/beuser/Configuration/Backend/AjaxRoutes.php
typo3/sysext/opendocs/Configuration/Backend/AjaxRoutes.php
typo3/sysext/recycler/Configuration/Backend/AjaxRoutes.php
typo3/sysext/rsaauth/Configuration/Backend/AjaxRoutes.php
typo3/sysext/t3editor/Configuration/Backend/AjaxRoutes.php
typo3/sysext/taskcenter/Configuration/Backend/AjaxRoutes.php
typo3/sysext/workspaces/Configuration/Backend/AjaxRoutes.php

```


* usually, I would look to see how the core does it (in newer or refactored extensions like ext:redirects), but the core itself usually, does not use Extbase. Concerning, the ajax handling however, I think that is irrelevant
* Maybe see ext:news for some pointers, specifically [AjaxRoutes](https://github.com/georgringer/news/blob/master/Configuration/Backend/AjaxRoutes.php), 
* for information about documenting, see https://docs.typo3.org/typo3cms/HowToDocument/ 
* optionally, ask for help in #typo3-documentation on [Slack](https://typo3.slack.com) or #typo3-cms-coredev on Slack. Do not use #typo3-cms-coredev for support questions, only for core related stuff.

Hope this helps.

**Comment by sypets** [comment]
Actually, there is another issue with the same scope: #61 

I am closing this issue, please use other issue for BE Ajax routes documentation
