### ISSUE TITLE
Link "Coding Guidelines" do not work

### ISSUE THREAD

**Issue by webfacer** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#267]
Looks like this link doesn´t exist anymore
https://docs.typo3.org/typo3cms/CodingGuidelinesReference/latest/PhpArchitecture/WorkingWithExceptions/Index.html

**Comment by sypets** [comment]
Thanks for pointing this out. The CGL reference has been moved to Core API. Please look here for the general core API: https://docs.typo3.org/typo3cms/CoreApiReference/CodingGuidelines/Index.html and here for the specific section: https://docs.typo3.org/typo3cms/CoreApiReference/CodingGuidelines/PhpArchitecture/WorkingWithExceptions.html

Some broken links are a known issue. While this is not ideal, it should solve itself within the search engines but will take some time. A general solution for adressing broken links will be adressed at a later time.

**Comment by webfacer** [comment]
thank you
