### ISSUE TITLE
Add information about deprecation log

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#274]
* [ ] Add information about deprecation log
* [ ] remove wiki page: https://wiki.typo3.org/Deprecation_Log

See also #600 as general issue for Wiki migration

**Comment by sypets** [comment]
https://blog.reelworx.at/detail/deprecation-log-handling-in-typo3-9/

**Comment by linawolf** [comment]
Please assign me to this topic. Seems like I cannot do it myself

**Comment by sypets** [comment]
Page https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Deprecation/Index.html exists

* [ ] Should get backported to older versions
* [ ] Check if Wiki page can be redirected and removed.

**Comment by sypets** [comment]
Closing, see #910
