### ISSUE TITLE
Typo3 Explained - Language probably wrong path

### ISSUE THREAD

**Issue by averlon** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#2742]
Hi,
in Typo3 Explained (Release: main) unter Language I find:
`EXT:my_extension/Configuration/Resources/Templates/MyTemplate.html`

shouldn't it be
`EXT:my_extension/Resources/Templates/MyTemplate.html`

This is used twice.

1. in the explanation of locallang.xlf for the standard path
2. in the explanation of locallang.xlf for LLL:EXT

Please check if I am not wrong.

**Comment by brotkrueml** [comment]
@averlon Thank you for reporting the issue. I attached a pull request for fixing this issue.
