### ISSUE TITLE
11.5 Documentation Fluid

### ISSUE THREAD

**Issue by averlon** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#2759]
Hi,
https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/Fluid/Introduction.html

After the sentence:
The template should include the sections which are to be rendered.

EXT:my_extension/Resources/Private/Layouts/Default.html

Is this realy "Layouts" or "Templates".

It is described under the section of "Layouts" but from my view it is an example for a Template.

Not sure - could you please check?

Regards
Karl-Heinz

**Comment by brotkrueml** [comment]
@averlon Yes, you are correct, this should be "Templates". Do you want to provide a PR? Best against "main" branch.

**Comment by averlon** [comment]
Hi Chris,
I am not a developer (trying to start now with my own extension) so I don't want to break something.
If you help me how to create a correct PR without breaking something I am glad to do so!

**Comment by brotkrueml** [comment]
> Hi Chris, I am not a developer (trying to start now with my own extension) so I don't want to break something. If you help me how to create a correct PR without breaking something I am glad to do so!

Best way for this small fix is to go to the documentation page of the main branch:
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Fluid/Introduction.html

Then can click on the "Edit on GitHub" button on the top. The repository is forked for your user, then you can adjust the wrong part in an editor. Then click on the button below the editor ("Propose file change"), and create a pull request.

It also also described here:
https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingDocsOfficial/GithubMethod.html
