### ISSUE TITLE
GitHub pipeline CI.yml fails

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#2773]
### Problem

GitHub rendering pipeline fails, for example: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/actions/runs/4449254865/jobs/7813175416?pr=2771

### Analysis

Today the 't3docs' Docker hub account together with with existing container images was removed. The error occurs since then. Problematic file: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/blob/main/.github/workflows/CI.yml 
This file has been used for rendering somewhen in the past but isn't needed any more nowaday. Nowadays rendering is done by using the GitHub hook to intercept, which in return uses the 'deploy' and 'rendering' piplines.

### Proposed solution

Remove the CI.yml file from all branches. Use the hook method instead.

**Comment by linawolf** [comment]
Is solved
