### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by franzholz** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#28]
1.) Why do you call the usage of "$GLOBALS['TYPO3_CONF_VARS']['SYS']['Objects'] " still XCLASS? It should be called "using System Objects" or similar. Since TYPO3 6.2 the name XCLASS should disappear from the manuals.

2.) What must be done if the array $GLOBALS['TYPO3_CONF_VARS']['SYS']['Objects']['TYPO3\\CMS\\Backend\\Controller\\NewRecordController'] already exists? Shall it be overwritten without any notice? Or is there any recommendation for an entry into an error log file?

3.) I cannot get System Objects class extending working with an abstract class.
"abstract class AbstractConditionMatcher extends \TYPO3\CMS\Core\Configuration\TypoScript\ConditionMatching\AbstractConditionMatcher {"
Are abstract classes not supported for extending them?

**Comment by marble** [comment]
Hello Franz, the documentation team is VERY small, and, for example, I'm not able to answer your questions. So I'd recommend to raise those questions in the appropriate mailing list. I guess [typo3-core] or [typo3-dev] is right. What do you think?

**Comment by xperseguers** [comment]
Hello Furthermore, I double that. Furthermore please always ask a single question with a ticket.
