### ISSUE TITLE
11.5 transport-smtp-stream-options are documented, but not implemented

### ISSUE THREAD

**Issue by martipoe** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#2883]
### Current behavior

The mail setting **transport-smtp-stream-options** is listed in the TYPO3 v11.5 documentation, but only implemented in v12.

### Expected behavior/output

If the setting does not exist for v11, it should not be documented for v11.

### Links

Documentation: https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/Configuration/Typo3ConfVars/MAIL.html#transport-smtp-stream-options

Issue relating to changes in v12: https://review.typo3.org/c/Packages/TYPO3.CMS/+/69907

I was unable to find commits for transport_smpt_stream_options in v11.5 branches: https://github.com/TYPO3/typo3/search?q=transport_smtp_stream_options

### TYPO3 versions

[11]

### Possible Solution

Remove the mail setting from the documentation until it is implemented for v11.5

**Comment by brotkrueml** [comment]
@martipoe Thanks for the hint, the option is now removed in v11 docs.
