### ISSUE TITLE
Update parts mentioning tce_db.php

### ISSUE THREAD

**Issue by tmotyl** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#296]
In few places in the documentation we still reference tce_db.php endpoint, which is long gone.
It was deprecated in 7.1
https://docs.typo3.org/typo3cms/extensions/core/7.6/Changelog/7.1/Deprecation-64922-DeprecatedEntryPoints.html
https://docs.typo3.org/typo3cms/extensions/core/Changelog/7.5/Breaking-68812-DeprecatedBackendEntrypointsMoved.html

for example here, there is a whole chapter about tce_db: https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Typo3CoreEngine/TceDb/Index.html

`tce_db` currently exists in the core as a route name to `/record/commit` path. See
typo3/sysext/backend/Configuration/Backend/Routes.php
```
    'tce_db' => [
        'path' => '/record/commit',
        'target' => Controller\SimpleDataHandlerController::class . '::mainAction'
    ],
```

We could also mention typo3/sysext/backend/Resources/Private/TypeScript/AjaxDataHandler.ts  javascript class.

See also change in the core removing last mentions of tce_db.php https://review.typo3.org/#/c/57636

**Comment by DanielSiepmann** [comment]
@tmotyl would you like to adjust the places as a first step?
