### ISSUE TITLE
ModifyFileDumpEvent contains examples of AfterFileCommandProcessedEvent

### ISSUE THREAD

**Issue by sgrossberndt** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#3057]
### Current behavior

The documentation of `ModifyFileDumpEvent` contains references to class `AfterFileCommandProcessedEvent` in the following example files:

* `EXT:my_extension/Configuration/Services.yaml`
* `EXT:my_extension/Classes/Resource/EventListener/MyEventListener.php`

### Expected behavior/output

Instead of class `AfterFileCommandProcessedEvent` the class `ModifyFileDumpEvent` must be used.

### Links

https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Events/Events/Core/Resource/ModifyFileDumpEvent.html

### TYPO3 versions

11, 12, main

### Possible Solution

have separate examples for the event listeners

**Comment by brotkrueml** [comment]
@sgrossberndt Thanks for the report.

**Comment by sgrossberndt** [comment]
Thanks for the quick fix!
