### ISSUE TITLE
unclear sentence in "File Storages" page of "Fal" documentation 

### ISSUE THREAD

**Issue by fawmi** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#311]
in page [File Storages
](https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Fal/Administration/Storages.html)
the sentence 

> This flag will generally not be set voluntarily

does not appear to be correct.  
does someone force you to set the flag if it is not set voluntarily?

**Comment by linawolf** [comment]
@flicstar any Idea how to improve this sentence?
