### ISSUE TITLE
Mention typo3conf/l10n path in composer mode

### ISSUE THREAD

**Issue by josefglatz** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#321]
Affected _TYPO3 Version: 9.5.x since https://review.typo3.org/57600_

---

Since the path to l10n folder is not hardcoded anymore, the documentation about this could be centralized mentioned in an upcoming Environment section of https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Index.html.

Then we can use http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#substitutions (http://docutils.sourceforge.net/docs/ref/rst/directives.html#replacement-text) to add abbreviations whenever `typo3temp/l10n` must be mentioned in an core documentation

**Comment by DanielSiepmann** [comment]
I've provided information about `Environment` within core API and updated all occurrences of l10n.
