### ISSUE TITLE
AssetCollector documentation contains unexplained references to WordPress documentation

### ISSUE THREAD

**Issue by duf-mo** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#3244]
### Current behavior
The [documentation on the AssetCollector](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Assets/Index.html#TYPO3\CMS\Core\Page\AssetCollector) contains a seemingly unrelated link to the documentation of WordPress' 'wp_enqueue_style' function:

```
Note on the implementation: - We use a Singleton to make use of the AssetCollector throughout Frontend process (similar to PageRenderer). - Although this is not optimal, I don't see any other way to do so in the current code.

https://developer.wordpress.org/reference/functions/wp_enqueue_style/
```

The link appears in the documentation for both TYPO3 v11 and v12. The WP Core function it is referencing does indeed solve a similar problem as AssetCollector does, but an explanation on how it is relevant there is missing.

### Expected behavior/output
Provide some context on why this WordPress function is being referenced here.

### Links
https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ApiOverview/Assets/Index.html#TYPO3\CMS\Core\Page\AssetCollector
https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/Assets/Index.html#TYPO3\CMS\Core\Page\AssetCollector
https://developer.wordpress.org/reference/functions/wp_enqueue_style/

### TYPO3 versions
11, 12

### Possible Solution
Either:
A) Include an explanation on how that function is relevant/comparable to AssetCollector 
OR 
B) Do not include the Link to 'wp_enqueue_style'.

**Comment by brotkrueml** [comment]
@duf-mo Thank you for your report. As the docs are rendered out of the code, I opened an issue on forge: https://forge.typo3.org/issues/101451 and provided a patch for TYPO3 Core: https://review.typo3.org/c/Packages/TYPO3.CMS/+/80180
