### ISSUE TITLE
SQL injection via TypoScript in GET/POST requests

### ISSUE THREAD

**Issue by lolli42** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#328]
This has been transferred from https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-Security/issues/14 - that repository has been inlined into 'core api'

In security chapter **Guidelines for Integrators**, section "TypoScript" [1], we explain the risk of SQL injection via TypoScript. Nothing is wrong with that, but I wonder if we should expand the code example, so that is also covers strings in GET/POST requests and also describe to parse/inject the argument properly and securely.

I am thinking about a code fragment, Jigal van Hemert posted in the English mailing list [2] in December 2014:
```
lib.products = CONTENT
lib.products{
    table = TABLE
    select {
        selectFields = name
        pidInList = 26506
        orderBy = name
        where = sid like ###GPSID###
        markers {
            GPSID.data = GP:SID
        }
    }
    renderObj = COA
    renderObj {
        10  = COA
        10  {
            10 = TEXT
            10.dataWrap ={field:name}[\n]
        }
    }
}
```
If someone is interested and has the time to re-work the code snippet and add the "argument as string" example, knock yourself out :-)  
The main point of the code above is that by using markers, values get escaped and quoted automatically if required.

[1] http://docs.typo3.org/typo3cms/SecurityGuide/GuidelinesIntegrators/Typoscript/Index.html
[2] http://lists.typo3.org/pipermail/typo3-english/2014-December/092321.html

**Comment by linawolf** [comment]
This got merged
