### ISSUE TITLE
Add advice regarding php executables in fileadmin

### ISSUE THREAD

**Issue by lolli42** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#329]
This has been transferred from https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-Security/issues/12 - that repository has been inlined into 'core api'

All files and folders can and should be write protected for the webserver/php user. However, `fileadmin/` and `typo3temp/` and `uploads/` cannot be write protected be definition. These folders should be excluded in the webserver configuration from executing PHP files.

Unconfirmed suggestion:  
> "*In a standard setup, TYPO3 CMS does not require to write into any directories other than fileadmin, typo3temp, typo3conf and upload. These directories can and should be write protected for the webserver/PHP user. Depending on the individual setup it is also recommended to prevent executing PHP files in the fileadmin and upload directory.*"

> Note: originally posted by Helmut Hummel as https://forge.typo3.org/issues/73031

**Comment by linawolf** [comment]
@lolli42 is this thill open? If so please reopen
