### ISSUE TITLE
Extend Security Guide by a chapter for developers

### ISSUE THREAD

**Issue by lolli42** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#330]
This has been transferred from https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-Security/issues/11 - that repository has been inlined into 'core api'

Several attempts have been made in the past to extend the TYPO3 Security Guide by a chapter for developers (*Guidelines for Extension Developers*). Some suggestions were for example:

* Information on SQL injections and Cross Site Scripting
* Explain process how to report a security issue in own extension to the Security Team
* Highlight that a fix for a security issue should be the only change in a release
* Explain the policy of "least disclosure" (used by the Security Team)
* List/summarize typical security vulnerabilities in PHP code (see CWE/SANS Most Dangerous Software Errors)
* Describe how to prevent these errors (maybe show code examples?)
* Explain which typical TYPO3 API functions should be used (?)
* Explain different HTML contexts and which API methods we have to sanitize values.
* Do not use second argument of `getLL()`
* Explain how FE session handling should be done by developers

The chapter should also include how to avoid SQLi properly, how to avoid XSS and a general recommendation to always use the TYPO3 API for validation, escaping and encoding.

It is best practice to make sure you always know which values are safe for output to the browser (htmlspecialchars, quoteJS) and which are not. A general rule we follow is to prepare variables in a raw form (putting together a title, a link or similar) and doing the actual encoding/safety later when outputting it. Another thing would be to make sure to typecast an integer-variable to (int) when you add it to HTML-output and not rely on that "some earlier part" would have made sure it's only a number.

https://forge.typo3.org/issues/50165
https://forge.typo3.org/issues/31672
https://forge.typo3.org/issues/71699
https://forge.typo3.org/issues/71701
https://forge.typo3.org/issues/79575
https://forge.typo3.org/issues/68167

**Comment by linawolf** [comment]
@lolli42 the section seems to be quite advanced now. Anything still missing? If so please make a new, specific Issue - or even better PR.
