### ISSUE TITLE
Keep and adjust section on ext:rsaauth

### ISSUE THREAD

**Issue by ohader** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#331]
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/commit/c69df8a5ddd276f2695182db94f3c7ccc795538f#diff-964d38cf737bc05439fbe8b8a08007ccL171

At least keep the part on ext:rsaauth (since it is still part of TYPO3 v9)
* describe what it really does
* advise to use HTTPS which makes the usage of ext:rsaauth superfluous
* describe what happens when using plain HTTP without having ext:rsaauth

**Comment by sypets** [comment]
and update current sysexts docs page: https://docs.typo3.org/typo3cms/SystemExtensions/Index.html to link to that info: 
![rsaauth](https://user-images.githubusercontent.com/13206455/48196998-8270f900-e354-11e8-934f-0b0bee805a95.png)
