### ISSUE TITLE
Replace prophecy with native mocking

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#3340]
### Current behavior

The Section about "Writing unit tests" currently uses the prophecy library.

### Expected behavior/output

That library is no longer shipped alongside with PHPUnit and needs to be installed manually. Many move away from that library and use PHPUnit native mocking instead.

### Links

- https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Testing/WritingUnit.html#mocking 

### TYPO3 versions

I guess 11 and 12, maybe even older versions

### Possible Solution

Replace mentions and examples to use PHPUnit own mocking.
We still can mention and link prophecy as an alternative.

### Additional context

This was brought up by an user on TYPO3 Slack. I've just opened the Issue so we can remove fraction and frustration from other users.

**Comment by linawolf** [comment]
It is solved for recent versions
