### ISSUE TITLE
TSconfig spelling

### ISSUE THREAD

**Issue by liayn** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#3396]
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/FileStructure/Configuration/TsConfig/Index.html

suggests "TsConfig" as spelling.

https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/GeneralConventions/Glossary.html
https://review.typo3.org/c/Packages/TYPO3.CMS/+/77725

suggest "TSconfig" as  spelling.

Either should be "fixed".

**Comment by brotkrueml** [comment]
We speak of "user TSconfig" and "page TSconfig".

However, the folder is named "TsConfig", at least in https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ExtensionArchitecture/FileStructure/Configuration/TsConfig/Index.html.
But here it is "TSconfig"  for the folder: https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ExtensionArchitecture/FileStructure/Configuration/Index.html

**Comment by brotkrueml** [comment]
Adjusted to `TsConfig` in the tree view with #3575. As also the Core used `TsConfig` until v11.5 (then the `Configuration/user.tsconfig` file was introduced) this should be the common spelling for folders.
