### ISSUE TITLE
Missing plugin type?

### ISSUE THREAD

**Issue by DavidBruchmann** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#3437]
### Current behavior

It's written there exist 3 ways to create Plugins, but the list shows only 2.

### Expected behavior/output

That the list count is according to the announcing number.

### Links

[CreatePlugins](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/ContentElements/CreatePlugins.html)

**Comment by sdelcroix** [comment]
I think this issue can be closed. 

The doc for main to 12.4 indicates and lists 2 ways. 
And the doc for 11.5 indicates and lists 3 ways.
