### ISSUE TITLE
Add proper production configuration to security guide

### ISSUE THREAD

**Issue by ohader** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#351]
What needs to be done when a website is live:

## Integrator

* Install Tool
  + switch to production context
  + disable debug exception handling (since this might expose database credentials in the worst case)
  + disable verbose error logging (e.g. not NOTICE anymore)

## Admin

* use proper channel encryption (HTTPS/TLS)
* logging configuration
  + setup proper logrotate configuration
  + in order to avoid DoS scenarios when NOTICE logs gets flooded

**Comment by sypets** [comment]
The debug / production context etc. is _partially_ already documented, but in a different context: https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/ErrorAndExceptionHandling/Examples/Index.html (would be a good idea to add a warning to Debug / Development section: Do not do this in production)

If someone tackles this topic, please consider that page as well and if possible not create duplicate content, but add links.

**Comment by linawolf** [comment]
Asked in Slack in #cig-security-advisories if anyone can take care of the issue.

**Comment by sypets** [comment]
I found another part where production settings is handled: 

https://docs.typo3.org/m/typo3/tutorial-getting-started/master/en-us/Installation/DeployTYPO3.html#production-settings

This is in "Getting started" > "Installation" > "Deploy. I think the installation guide is a good place for this.

@ohader Is this sufficiently handled for you? Should we refer to it in the security guide or is it ok to close here? I added some PR:


* for HTTPS, I added a PR: https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted/pull/179
* about logging, added PR: https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted/pull/180

**Comment by linawolf** [comment]
all commits merged
