### ISSUE TITLE
Update code snippets to work with namespaces

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#353]
* [ ] https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/ErrorAndExceptionHandling/Extending/Index.html
* [ ] https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Examples/ContentElementWizard/

**Comment by FelHell** [comment]
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Examples/ContentElementWizard/ has already been updated and I didn't find any code snippets that should be updated.

**Comment by sypets** [comment]
@FelHell Yes, this page was recently updated. Thanks for pointing this out. I think we can close this issue.

**Comment by FelHell** [comment]
@sypets In https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/ErrorAndExceptionHandling/Extending/Index.html the namespaces were missing. I added them in 297bc62868eb0b027869e3571b6376dbfc267da5 and then we could close the issue. I'm not sure about the `ext_localconf.php` part, as written on https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ConfigurationFiles/Index.html.
