### ISSUE TITLE
Readability of section on executeQuery() vs. executeStatement()

### ISSUE THREAD

**Issue by kitzberger** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#3557]
It took me 5 minutes to figure out what this hint tried to tell me:

![image](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/assets/1405149/c3b67758-ceb3-4cb5-b701-30a3bacc4191)

https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Database/QueryBuilder/Index.html#executequery-and-executestatement

I suggest adding some line breaks?

**Comment by brotkrueml** [comment]
@kitzberger Feel welcome to provide a PR ;-)
