### ISSUE TITLE
Rethink overuse of the include directive

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#356]
# How include is used

Include can be used to include small .rst.txt snippets. The format for these snippets are .rst, but we agreed to name them .rst.txt. It can be used to include a common text in more than one place:

`.. include:: StagingServers.rst.txt`

# Problem

Current problems, see what Martin wrote: https://docs.typo3.org/typo3cms/HowToDocument/WritingReST/IncludingFiles.html#disadvantages

Currently, in a number of places, includes are used to include a text snippet in only one place. You only get the disadvantages of using include like this, there is (IMO) no advantage. 

Example:

https://docs.typo3.org/typo3cms/CoreApiReference/_sources/Security/GeneralGuidelines/Index.txt

# My suggestion

* do not use include where there is no advantage
* At least, for small snippets, do not include the headline in the .rst.txt file. Add the headline, where the text is included.

**Comment by lolli42** [comment]
I used this deliberately for the sec guide integration - it made sense to do so: The main benefit is that it ends up with relatively long main chapters with all content on one page without having the user clickling around on hundreds of single pages.
The alternative is to inline the .rst.txt content directly into the using .rst files. I've put quite some time into creating a useful menu and at the same time avoing all these mini text blocks on single pages and found this solution a useful trade-off.

**Comment by sypets** [comment]
@lolli42 

I agree, it's better to have it on one page for easy reading, rather than clicking through pages with very little content. 

I would vote for putting it in **one** file though (without includes), see aforementioned caveats, especially:

* easier for people to edit directly by "Edit me on Github"
* you get syntax highlighting for .rst files
* the Github preview will probably also work better for .rst than for .rst.txt

Additionally, the  header labels for the sections in https://raw.githubusercontent.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/latest/Documentation/Security/GeneralGuidelines/Index.rst currently do not work. Try creating a cross-reference link:

:ref:`security-updating-extensions`

A little weird. At first I thought you need a newline between label and header, but it does work if you put the label in the included file, see https://raw.githubusercontent.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/latest/Documentation/Security/GeneralGuidelines/StagingServers.rst.txt

Anyway, I'll create a PR and you can see if you are happy with result ...
