### ISSUE TITLE
Adjust section on handing in reviews to security team

### ISSUE THREAD

**Issue by ohader** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#365]
https://docs.typo3.org/typo3cms/CoreApiReference/Security/SecurityTeam/Index.html

* security team just does not have the capacity to review individual extensions or project
* (this is different in case there is a specific report about vulnerabilities)
* section should be adjusted and probably point to TYPO3 GmbH's "review" product

Reasons for the security team are basically:
* these kind of reviews cannot be done for free
* it's not clear reviews should be charged (rate, process, handling)
* it's not possible that the security team provides any warranty
* in case "reviewed extensions" should be reestablished, this has to be triggered and organized by TYPO3 Association since much more teams and aspects need to be involved

The section has been integrated with https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-Security/commit/6c70a23df23eee7f7d8ea1504b2102af5df848f3#diff-2df145e78fdd86adcc663f3d7c75980c

**Comment by linawolf** [comment]
@flicstar could you maybe turn above list into a PR? Or @ohader could you provide a PR yourself?

**Comment by flicstar** [comment]
I see now that @ohader has self-assigned this. Without knowing that, I spoke to Schamsy this morning (Michael Schams) and he took a look and said "To be honest, I'd just get rid of this paragraph." 

I created PR 33 for older version of Security Guide: https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-Security/pull/33


And I also created PR #1265 to try to address this issue.

**Comment by linawolf** [comment]
PRs are merged
