### ISSUE TITLE
ActionController: Document how to access tt_content uid

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#3928]
### Current behavior
As a developer who writes a frontend plugin, I want to find information how to fetch file references for the content element.
[Fetching FAL references](https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ApiOverview/Fal/UsingFal/ExamplesFileFolder.html#getting-referenced-files) is there, but it talks about pages.

Neither there nor on the ActionController docs is explained how to obtain the current tt_content uid.

### Expected behavior/output
The FAL reference example - or the ActionController docs - should explain how to obtain the UID of the current tt_content element.

```
$this->configurationManager->getContentObject()->data['uid'];
```

### Links
- https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ExtensionArchitecture/Extbase/Reference/Controller/Index.html
- https://stackoverflow.com/questions/10447983/get-tt-content-uid

### TYPO3 versions

12

**Comment by brotkrueml** [comment]
I assume, that would be the way (regardless of Extbase or non-Extbase):
https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ApiOverview/RequestLifeCycle/RequestAttributes/CurrentContentObject.html

**Comment by cweiske** [comment]
Thanks for the info.
