### ISSUE TITLE
Outdated information about `ext_tables_static+adt.sql`

### ISSUE THREAD

**Issue by nhovratov** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#3964]
It is stated, that you can add a `drop table` to the statement. But the Core only handles `INSERT INTO` statements.

The ability to define any other statements seems to be gone missing with https://review.typo3.org/c/Packages/TYPO3.CMS/+/49593
Unfortunately without a breaking.rst back then.

This is the old code. Apparently TYPO3 always used to run a DROP TABLE statement anyway.
Currently if ext_tables_static+adt.sql is edited, TYPO3 automatically truncates the table and inserts the records anew.

```
    public function importStaticSql($rawDefinitions)
    {
        $statements = $this->installToolSqlParser->getStatementArray($rawDefinitions, 1);
        list($statementsPerTable, $insertCount) = $this->installToolSqlParser->getCreateTables($statements, 1);
        $db = $this->getDatabaseConnection();
        // Traverse the tables
        foreach ($statementsPerTable as $table => $query) {
            $db->admin_query('DROP TABLE IF EXISTS ' . $table);
            $db->admin_query($query);
            if ($insertCount[$table]) {
                $insertStatements = $this->installToolSqlParser->getTableInsertStatements($statements, $table);
                foreach ($insertStatements as $statement) {
                    $db->admin_query($statement);
                }
            }
        }
    }
```

I propose to update the documentation to state that only INSERT INTO statements are allowed and that drop table is handled automatically if contents of the sql file change.

https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/blob/main/Documentation/ExtensionArchitecture/FileStructure/ExtTablesStaticAdtSql.rst

**Comment by brotkrueml** [comment]
@nhovratov Thanks for reporting this :+1:. Please have a look at the PR. Personally, I haven't worked with static data.
