### ISSUE TITLE
Update information about importing / installing extensions to include composer installation (8.7)

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#406]
On the page https://docs.typo3.org/typo3cms/CoreApiReference/8.7/ExtensionArchitecture/Installation/Index.html#installing-extensions information about installing with Composer is missing.

Add information about installing with Composer [as done in newer versions](https://docs.typo3.org/typo3cms/CoreApiReference/8.7/ExtensionArchitecture/Installation/Index.html#installing-extensions).

Tip: Do not add too much text, link to [Installation Guide](https://docs.typo3.org/m/typo3/guide-installation/master/en-us/ExtensionInstallation/Index.html) instead.

# Tips for new contributors

* Either edit the page directly, using the ["Edit me on GitHub"](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocsOfficial/GithubMethod.html) button on upper right of page
* If you are familiar with Git and Docker, you can use the "[Local editing and rendering with Docker](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocsOfficial/LocalEditing.html)" workflow
* Check out the [reST & Sphinx cheat sheet](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/CheatSheet.html)
* for linking to sections in other manuals, use [cross references](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/CheatSheet.html#cross-references), e.g. link to section Extension Installation in Installation Guide with: 

    :ref:\`t3install:extension-installation\`

**Comment by linawolf** [comment]
The page doesn't exist in newer versions anymore and the information is availible in the installation guide.
