### ISSUE TITLE
3 spelling errors in the main diagram of the introduction

### ISSUE THREAD

**Issue by sandoba** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#4071]
As mentioned in https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/4070 there are currently 3 spelling errors in the main diagram of the introduction at https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Introduction/Index.html.

See: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/blob/51f04cd439fa3ff6989f2130b0e02c2431d9c467/Documentation/Introduction/Index.rst + https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/blob/main/Documentation/Images/Graphics/Typo3CmsStructure.png

"Costomization" > "Customization"
"Ingteraction" > "Interaction"
"Database Sever" > "Database Server"

I did not fix those directly as I don't know the specific font used.

**Comment by linawolf** [comment]
Unfortunary we do not have an original file for this graphic. Could you imagine providing a new one. I believe either SVG or https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingReST/Reference/Graphics/Diagrams.html could be a good source

**Comment by sypets** [comment]
Link to image: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Images/Graphics/Typo3CmsStructure.png

Copying image for reference in the future. 

![Typo3CmsStructure](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/assets/13206455/341f0ec7-8dd8-474f-990b-93b54f66a22e)

**Comment by linawolf** [comment]
We would need the image in a format that can be editet, like svg or https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingReST/Reference/Graphics/Diagrams.html
