### ISSUE TITLE
Sliding Window Pagination example is wrong

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#4164]
### Current behavior
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Pagination/Index.html

The "sliding window pagination" docs say:

> Example: Imagine 1000 records and 20 items per page which would lead to 50 links. Using the SlidingWindowPagination, you will get something like < 1 2 ... 21 22 23 24 ... 100 >.

This is not correct. The pagination will only give you "21 22 23 24", but not 1, 2, "..." and 100.

### Expected behavior/output

The example needs to be corrected or the example code adjusted, so that "< 1 2 ..." are generated by its output.

### Links
- https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/4
- https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/1866

### TYPO3 versions
main, 12

**Comment by linawolf** [comment]
@cweiske , thanks for reporting it. Wouldnt the actual output depend on the templates used? The exact output example is mentioned like that in changelog that  you cite?

**Comment by cweiske** [comment]
The template only renders the links that the pagination creates.
I think the changelog is wrong.
