### ISSUE TITLE
Should new upgrade wizard API (UpgradeWizardInterface) be used by third party extensions?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#419]
Changelog says no: **"The new interface classes are available in the core and will be used in the core update wizards as a next step. They should not yet be used by third parties."**

https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/9.4/Feature-86076-NewAPIForUpgradeWizards.html

But the section [Upgrade Wizards](https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/UpdateWizards/Creation.html) in "TYPO3 Explained" uses new API (and not older method of inheriting from AbstractUpdate).

Probably best to update one of the sources: either it is to be used by extensions or not.

**Comment by sypets** [comment]
Probably also a good idea to clarify scope of manual: #420. There are some things, that are differently if developing in the core or developing third party extensions (e.g. upgrade wizards).

**Comment by susannemoog** [comment]
The ChangeLog entry was relevant at that time (9.4, first version) - there they should **not yet** be used. With stab phase and the release of 9.5 the API is considered stable (after https://forge.typo3.org/issues/86172 were fixed and the API used for "real life" cases.

**Comment by sypets** [comment]
will change changelog entry in core: https://forge.typo3.org/issues/87834
