### ISSUE TITLE
Please clarify scope of this manual

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#420]
"This document is intended to be a reference for TYPO3 CMS developers and partially for integrators." from [Introduction](https://docs.typo3.org/typo3cms/CoreApiReference/Introduction/Index.html).

I would probably interpret "TYPO3 CMS developers" to mean TYPO3 core developers, but I always assumed this manual was rather for extension developers _using_ the core  (and not developing the core). Of course, a lot of the material is relevant for both but I do think for readers and contributors to this manual, we should be very clear about the intended audience.

**Comment by susannemoog** [comment]
`TYPO3 CMS developers` is for me every developer working with TYPO3 (extension author or core) - but focus on the "working **with** TYPO3" instead of **on** TYPO3. (so you are correct that it's more about TYPO3 Extension Developers.

**Comment by linawolf** [comment]
There is not really anything that can be done to resolve this issue....
