### ISSUE TITLE
No documentation for data handler hooks

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#4526]
### Current behavior
When searching for "processDatamapClass" on docs.typo3.org, no results are found.

### Expected behavior/output
[Datahandler](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/DataHandler/Index.html) hooks should be documented.

Keywords:
- `$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_tcemain.php']['processDatamapClass'][]`
- `processDatamap_afterDatabaseOperations`

**Comment by linawolf** [comment]
We have never documented Hooks. Once they are turned into events we will document them.
