### ISSUE TITLE
Duplicate content: Backend interface

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#455]
Not everything can be immediately merged. Sometimes the scope is different. Should be checked ...

[Backend interface](https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/BackendModules/Structure/Index.html) and [Getting Started: General Backend Structure](https://docs.typo3.org/typo3cms/GettingStartedTutorial/GeneralPrinciples/GeneralBackendStructure/Index.html) is nearly identical.

In one we have the "page tree", which could be regarded as a specific implementation of the "navigation frame". In the other we have the "navigation frame"

**Comment by linawolf** [comment]
Getting started and TYPO3 Explained have different scopes and explainations
