### ISSUE TITLE
Re-Add missing information about storing information in session

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#458]
Back in the days there was a documentation about how to store and retrieve values from a session: https://docs.typo3.org/typo3cms/TyposcriptReference/6.0/AppendixC/StoringData/Index.html#storing-user-data-or-session-data

This was removed and is missing now. This information should be added at Core API again, maybe at https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/SessionStorageFramework/Index.html

Afterwards there should be a reference from new TypoScript condition reference for fetching information from session.

**Comment by sypets** [comment]
The documentation from 6.0 is still there in an older branch (that is not rendered):

https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/blob/6-0/Documentation/AppendixC/StoringData/Index.rst

**Comment by sypets** [comment]
Also, what about storing session data in backend?

**Comment by linawolf** [comment]
Closing this Issue as it was idle for more then a year.
