### ISSUE TITLE
Document backend routes / AjaxRoutes

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#459]
**entry points for documentation:**

* https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/JavaScript/Ajax/Backend/Index.html
* https://docs.typo3.org/typo3cms/CoreApiReference/latest/ApiOverview/BackendRouting/Index.html

**questions:**

* how is "ajax id" constructed (presumably from 'path' in AjaxRoutes.php with prefix `/ajax/`?
* what are the parameters in Routes.php and AjaxRoutes.php?
* define terms: e.g. "identifier", "ajax id" (or "ajax route"?), "path", "route" etc. 
* What is for example used in returnURl in [EditRecord ViewHelper](https://docs.typo3.org/typo3cms/ViewHelperReference/typo3/backend/latest/Uri/EditRecord.html)?
* or for "route" parameter in [be.uri ViewHelper](https://docs.typo3.org/typo3cms/ViewHelperReference/typo3/fluid/latest/Be/Uri.html)?

Related:

* [SCRIPTING-BASE: AJAX with PSR-7](https://scripting-base.de/blog/ajax-with-psr-7.html)
* [SCRIPTING-BASE: PSR-7 for backend modules](https://scripting-base.de/blog/psr-7-for-backend-modules)
* StackOverflow: [TYPO3 Ajax in Backend Extension](https://stackoverflow.com/questions/16239174/typo3-ajax-in-backend-extension)
* Changelog: https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/7.6/Breaking-69916-RegisteredAJAXHandlersReplacedByRoutes.html
* core:  typo3/sysext/*/Configuration/Backend/AjaxRoutes.php
* core: typo3/sysext/*/Configuration/Backend/Routes.php
* TYPO3 Explained for 8.7

**Comment by sypets** [comment]
I just found this section, which I had missed before: https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Http/Index.html#routing

**Comment by linawolf** [comment]
There where related merges
