### ISSUE TITLE
Wrong Path for user.tsconfig in TYPO3 13 on https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us//ExtensionArchitecture/FileStructure/Configuration/TsConfig/Index.html

### ISSUE THREAD

**Issue by Tishwings** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#4688]
### Current behavior

Wrong Path for User.tsconfig File in TYPO3 13 (main) is provided.

### Expected behavior/output

For TYPO13 the user.tsconfig file has another place now, as listed in the TSconfig reference: https://docs.typo3.org/m/typo3/reference-tsconfig/main/en-us/UsingSetting/UserTSconfig.html

>  New in version 13.0
>  Starting with TYPO3 v13.0 user TSconfig in a file named Configuration/user.tsconfig in an extension is automatically loaded during build time.

### Links

Link to current main Core documentation with wrong information: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/FileStructure/Configuration/TsConfig/Index.html

Link to TSConfig documentation with correct information: https://docs.typo3.org/m/typo3/reference-tsconfig/main/en-us/UsingSetting/UserTSconfig.html

### TYPO3 versions

13

### Possible Solution

Update Text, check for other wrong tsconfig paths on build time?

**Comment by linawolf** [comment]
Thank you for your report, @Tishwings. Actually you can still store user TSconfig in the path Configuration/TsConfig/User and it will probably be common practice to do so in TYPO3 13 and above.

The Configuration/user.tsconfig can be used for **global** inclusion of user tsconfig. However, when you have different tsconfig for different user groups it would not make sense to include them globally.

The file user.tsconfig is already listed here: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us//ExtensionArchitecture/FileStructure/Configuration/UserTsconfig.html
