### ISSUE TITLE
Clarify the scope of TCA/Overrides files.

### ISSUE THREAD

**Issue by dogawaf** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#4756]
### Current behavior

The documentation is not clear about the scope of variables in TCA files. The examples use `call_user_func` to wrap variable declaration in an inconsistent way.

### Expected behavior/output

The documentation should inform the developer about the scope of variables in TCA files, according the current TYPO3 version. The examples should be state-of-the-art and consistent.

### Links

https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/HowTo/ExtendingTca/Examples/Index.html : fix examples and add a "attention" block

https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/HowTo/ExtendingTca/StoringChanges/Index.html : maybe add a entire section about scope?

### TYPO3 versions

All, with a change since TYPO3 12.

### Possible Solution

**For 12+:** 
- unwrap examples with call_user_func
- add a hint block about the scope of the files: "_Since v12, TCA files are now locally scoped. This means that a variable declared in a file will not leak into the global scope._"

**For 11 and below:** 
- wrap examples with call_user_func 
- add a hint block about the scope of the files: "_TCA files are concatenated into the same variable scope. This means that a variable declared in a file can will exists in all subsequant files. A workaround is to wrap your code with call_user_func_"

**Comment by dogawaf** [comment]
I am preparing a PR for main branch. 
I am not sure about how to backport the change to earlier version of TYPO3, I certainly need help for that.

**Comment by linawolf** [comment]
PR is merged and backported
