### ISSUE TITLE
Side menu should not scroll, when scrolling main content area.

### ISSUE THREAD

**Issue by rowild** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#476]
When the sidebar and the main content area of a documentation page have content that overflows y, e.g. `https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Database/QueryBuilder/Index.html`, both areas start scrolling, even though only scrolling on the main content area is desired. IMO a selected menu should always stay in focus, scrolling of nav and main content should be independent from each other (which it is, when only the nav area is scrolled).

It would work, if the main content would also define its own `position:absolute; overflow-x:scroll` and some other CSS. (PR will follow.)

**Comment by linawolf** [comment]
cannot reproduce anymore
