### ISSUE TITLE
CLI command documentation advertises incompatible 3rd party package helhum/typo3-console

### ISSUE THREAD

**Issue by o-ba** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#4881]
The  documentation references `helhum/typo3-console` - but this package is not even ready for TYPO3 v13. The documentation should not advertise incompatible 3rd-party packages.

Move from TYPO3 Core Bug tracker: https://forge.typo3.org/issues/105431

**Comment by garvinhicking** [comment]
TYPO3-Console is now compatible with v13.4, so I'm closing this. I think recommending this long-standing package is fair, and giving OSS maintainers a bit breathing room supporting fresh releases is fair. (This is not aimed at you, Oli :-D )
