### ISSUE TITLE
Add documentation regarding PSR-15 middleware integration

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#515]
This knowledge is necessary to be come a certified integrator. Therefore this should be official documented.

Sources that might be useful while writing:
* https://usetypo3.com/psr15-middleware-in-typo3.html
* https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.2/Feature-83725-SupportForPSR-15HTTPMiddlewares.html

https://my.skilldisplay.eu/skill/505/37

**Comment by sypets** [comment]
Thank you!!! :thumbsup: That would be great. 

Btw, I asked Daniel Goerz from usetypo3 at the TYPO3 camp Berlin if we can reuse some of his [blog entry about the topic](https://usetypo3.com/psr15-middleware-in-typo3.html). He was ok with it. Don't know if this is even necessary, but it could save time and work.
