### ISSUE TITLE
Problem on https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us//Testing/FunctionalTesting/Index.html

### ISSUE THREAD

**Issue by BugHunter2k** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#5151]
### Current behavior

https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Testing/FunctionalTesting/Index.html#database-fixtures

Reading through that page I noticed the code under "Simple Example" is reused multiple times (Loaded extensions, Database fixtures, Loading files). The Code is not relevant to e.g. Loading Files and does not have any match with the surrounding text.

### Expected behavior/output

Examples should help with the associated text.

### Links
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Testing/FunctionalTesting/Index.html#database-fixtures

### TYPO3 versions

[12, 13]

### Possible Solution

Create matching exapmles

**Comment by garvinhicking** [comment]
Created a PR that should fix this. Thanks for reporting+spotting this! :-)
