### ISSUE TITLE
Wrong documentation for $GLOBALS['TYPO3_CONF_VARS']['FE']['additionalCanonicalizedUrlParameters']

### ISSUE THREAD

**Issue by o-ba** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#5152]
The documentation of the setting differs from the official changelog entry https://docs.typo3.org/permalink/changelog:important-86577, the description of the setting in TYPO3 Core itself as well as corresponding code place https://github.com/TYPO3/typo3/blob/main/typo3/sysext/frontend/Classes/Utility/CanonicalizationUtility.php#L40. Instead of excluding, this setting is to add additional parameters to the canonicalized url.

**Comment by garvinhicking** [comment]
On it

**Comment by garvinhicking** [comment]
Affected pages:

https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Configuration/Typo3ConfVars/FE.html
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Seo/CanonicalApi.html

Thanks for forwarding this here. Created a PR that hopefully properly reflects the right logic.
