### ISSUE TITLE
Document how to access and write Flexforms

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#520]
This is necessary to become certified developer and should therefore be documented.

Sources:
* https://docs.typo3.org/m/typo3/reference-tca/master/en-us/ColumnsConfig/Type/Flex.html
Sourcecode

https://my.skilldisplay.eu/skill/279/37

**Comment by sypets** [comment]
There was already an issue #305. I will close this if that's ok with you.
