### ISSUE TITLE
Plan for systematic review: API overview

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#537]
This is a list for determining if current content is up to date. Check off checkmark if content is reasonably up to date in current master (10.0). If you find a problem, fix it or create an issue.

BASICS

* [ ] Directory Structure
* [ ] PHP Namespaces
* [ ] Environment
* [ ] Variables and Constants

BOOTSTRAPPING

* [ ] autoloading
* [ ] Bootstrapping

PERSISTENCE

* [ ] Database
* [ ] TYPO3 Core Engine (TCE)
* [ ] Digital Assets Management (FAL)

CONFIGURATION

* [ ] TypoScript Syntax
* [ ] User and Page TSconfig
* [ ] User Settings Configuration
* [x] FlexForms (was just added)

CACHING

* [ ] Caching Framework

LOGGING, ERRORS, EXCEPTIONS

* [ ] Logging Framework
* [ ] System Log
* [ ] Error and Exception Handling

BACKEND

* [ ] Backend Access Control
* [ ] Backend Modules
* [ ] Backend Routing
* [ ] Backend User Object
* [ ] FormEngine
* [ ] JavaScript in TYPO3 Backend
* [ ] Flash Messages

HANDLING SITES, URLS, LANGUAGES

* [ ] Site Handling
* [ ] Internationalization and Localization

SECURITY, AUTHENTICATION, PASSWORDS, 

* [ ] Authentication
* [ ] Password Hashing
* [ ] Form Protection Tool

UPDATES

* [x] Update Wizards
* [x] Extension Scanner (was added recently, should be up to date)

SEO & SOCIAL MEDIA

* [ ] MetaTag API (SEO)
* [ ] PageTitle API
* [ ] XML Sitemap

VARIOUS

* [ ] Command Line Dispatcher (Symfony)
* [ ] Context API and Aspects
* [ ] Context Sensitive Help (CSH)
* [ ] Enumerations
* [ ] Feature Toggles
* [ ] HTTP Request Library / Guzzle / PSR-7
* [ ] Hooks and Signals
* [ ] Icon API
* [ ] Locking API
* [ ] Mail API
* [ ] Page Types
* [ ] Rich Text Editors (RTE)
* [ ] Session Storage Framework
* [ ] Services
* [ ] Soft References
* [ ] System Categories
* [ ] System Collections
* [ ] Using the System Registry
* [ ] Versioning and Workspaces
* [ ] Extending Classes (XCLASSes)

**Comment by linawolf** [comment]
@sypets  are you still working on this? It has been idle for more then a year
