### ISSUE TITLE
How to structure configuration? 

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#545]
Currently, we describe configuration in 2 (and more) places.

1. Extension Development with [Files and Locations](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/FilesAndLocations/Index.html), [Configuration Files (ext_tables.php & ext_localconf.php)](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ConfigurationFiles/Index.html), [Extension Configuration](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ConfigurationOptions/Index.html), [Extending the TCA array](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ExtendingTca/Index.html)
2. API Overview: [TypoScript syntax](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/TypoScriptSyntax/Index.html), [User & Page TSconfig](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Tsconfig/Index.html)
3. "Introduction" sections in TypoScript reference, TSconfig reference etc.

The scope is slightly different: the extension section walks you through the files and directories used by the extension while the API overview just lists a subset of configuration topics (with some things missing or documented elsewhere). However, this results in a weird order. You have an overview of the files before the concepts of configuration are explained. 

Especially the page on [ext_tables.php & ext_localconf.php](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ConfigurationFiles/Index.html) has a list of things that should be in the files (e.g. include TSconfig, TypoScript etc.) without any examples, links or an explanation what these things are. 

I don't know how to resolve this right now, but I think we need to look at some things on a more global perspective, e.g. how should TYPO3 Explained be structured, is it a reference and only a reference? If yes, do we have documentation for starting developers that walks them through everything and explains things step by step? We already have that for Extbase / Fluid. But that covers basically Extbase / Fluid. Where do we cover other topics for beginning developers? What should be put in the "Getting Started Tutorial".

The problem is, you can hardly do anything in the documentation without being confronted with these general questions. If the general questions are not clarified and handled (hopefully) mostly the same way (**this means we must find a common understanding how it should be done and communicate this**), it is difficult to create consistent documentation and it is difficult for all contributors (not just me) to make any changes.

**Comment by linawolf** [comment]
@sypets are you still working on this? It has been lying idle since more then a year
