### ISSUE TITLE
[TASK] Document fields of FAL tables like CSH

### ISSUE THREAD

**Issue by erredeco** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#549]
The issue https://forge.typo3.org/issues/56370 asked to add CSH to some FAL tables to help people understand what the fields are used for, but CSH will be removed on TYPO3 version 10.

I write this task to keep track of this request; as far as I see on https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Fal/Architecture/Database.html#database-structure there is already an explanation of the tables used by FAL, but no explanation of the individual fields. 
On a side note, maybe all the information that is now part of CSH should be part of an "editor" manual or "integrator manual".

thank you.

[UPDATE] - as stated on https://decisions.typo3.org/t/drop-context-sensitive-help-in-core/511/17 the CSH could be kept for a while - put this issue on on hold (or cancel it if you prefer)

**Comment by linawolf** [comment]
Ok, thanks, I will close it
