### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by sascha307050** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#56]
TYPO3CMS-Reference-CoreApi/Documentation/ApiOverview/Index.rst

There is a 404 Error: http://typo3.org/documentation/api/
It should be: http://api.typo3.org/

Please correct me if I am wrong!

**Comment by marble** [comment]
Indeed! Great, you have entered level 1 of collaboration. To reach the next level: Edit the text yourself next time you encounter an error! Anyway, thank you!

**Comment by sascha307050** [comment]
Okay thank you!!!
