### ISSUE TITLE
Add YouTube videos

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#573]
for speaking URLs

* [ ] https://www.youtube.com/watch?v=dUz4B08XFes 

See information about embedding YouTube videos: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/YoutubeVideos.html

**Comment by linawolf** [comment]
Pushing this: Who would like to do this?
