### ISSUE TITLE
TYPO3 10: Document PSR-14 based EventDispatcher

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#594]
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-88770-PSR-14BasedEventDispatcher.html

**Comment by linawolf** [comment]
Talk by Benni to the topic: https://youtu.be/ElUDMXmV3Ng

**Comment by sypets** [comment]
Resolved with #616
