### ISSUE TITLE
Move things from the Wiki

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#600]
* [ ] https://wiki.typo3.org/Backend_Programming
* [ ] information about deprecation log(https://wiki.typo3.org/Deprecation_Log), see #274
* [x] FlexForms: https://wiki.typo3.org/Extension_Development,_using_Flexforms

----

* [ ] IRRE: https://wiki.typo3.org/Inline_Relational_Record_Editing (this is not really documentation, but rather a blueprint. However, documentation about IRRE does not exist on docs.typo3.org?)

> replace link core: `typo3/sysext/core/Tests/Functional/Fixtures/Extensions/irre_tutorial/README.txt`

----

* [ ] http://wiki.typo3.org/ComposerClassLoader

> replace link in core: `typo3/sysext/core/Documentation/Changelog/7.1/Deprecation-64361-ComposerClassLoading.rst`

---

* [ ] https://wiki.typo3.org/Opcode_Cache

> Also replace links in core:
> `typo3/sysext/core/Classes/Core/SystemEnvironmentBuilder.php`
> `typo3/sysext/core/Classes/Information/Typo3Information.php`

---
* [ ] http://wiki.typo3.org/Dependency_Injection

> Create page [Dependecy Injection](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/DependencyInjection/Index.html) in older branches?

**Comment by susannemoog** [comment]
All content migration pages are handled by https://github.com/TYPO3-Documentation/T3DocTeam/issues/154 (taken from the real-life analytics data about what content is still needed). Closing this issue here, to handle the migration in one place.
