### ISSUE TITLE
Connection::PARAM_INT_ARRAY out of context

### ISSUE THREAD

**Issue by DavidBruchmann** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#602]
In `TYPO3CMS-Reference-CoreApi/Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst` in the examples is `Connection::PARAM_INT_ARRAY` used.
It's not mentioned or explained what `Connection` is, where it's coming from.

**Comment by DavidBruchmann** [comment]
should be `\TYPO3\CMS\Core\Database\Connection::PARAM_INT_ARRAY` or some mention about the namespace.

**Comment by DanielSiepmann** [comment]
Would you like to provide a small pull request?

**Comment by ayacoo** [comment]
Is not the "use" displayed directly above it?

**Comment by mbrodala** [comment]
Correct:

![image](https://user-images.githubusercontent.com/5037116/66053997-9e185b80-e533-11e9-83ec-3b692af7001c.png)

**Comment by ayacoo** [comment]
So we can close this issue? 🤔

**Comment by DavidBruchmann** [comment]
sorry, you're right ;-)
