### ISSUE TITLE
Missing Section on Backend Layout

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#629]
all information when googling for "typo3 backend layout" seems to come from other sources like blogs. 
We could use this video': https://www.youtube.com/watch?v=RoHaeo4fq34 by Benji

maybe some information from jweiland (License issues?)
https://jweiland.net/typo3/beispiele-anleitungen-faq/allgemeines/backendlayout-einsetzen.html

maybe some information from the sitepackage:
https://docs.typo3.org/typo3cms/extensions/sitepackage/stable/BackendLayouts/CreatingBackendLayouts/Index.html

And information from the changelog i.e.
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/7.4/Feature-61903-PageTSDataproviderForBackendLayouts.html
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Important-81109-SimplifyDefaultBackendLayout.html
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/7.5/Feature-69602-SimplifyHandlingOfBackendLayoutsInFrontend.html

Please assign me to the task, I dont seem to be able to assign myself

**Comment by sypets** [comment]
Chapter on BE Layouts was written so I would like to close this.

https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/BackendLayout/Index.html

Please feel free to reopen if something is still missing or create a new issue.
