### ISSUE TITLE
Tune acceptance tests chapter

### ISSUE THREAD

**Issue by tmotyl** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#631]
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/Testing/WritingAcceptance.html
In general it looks quite good, just 2 minor things are missing
1) a pointer the user to first read https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/Testing/CoreTesting.html before reading this chapter
2) Scripts/runTests.sh usage example to trigger acceptance tests

**Comment by linawolf** [comment]
@alexander-nitsche can you maybe help with this issue?

**Comment by alexander-nitsche** [comment]
hi @tmotyl ,

i added a link to the "Extension Testing" chapter which contains a whole setup for acceptance tests using the `runTests.sh`. This is in line with the "Writing Functional Tests" chapter, which links to "Extension Testing" chapter too and makes clear, that the "Writing Unit/Functional/Acceptance Tests" chapters are about writing the PHP tests with support of the `typo3/testing-framework` and not about setting up the testing environment.

**Comment by tmotyl** [comment]
Thanks @alexander-nitsche, it's much better thanks to your change. However its still hard to find how to execute acceptance tests, especialy when you want to run the core and not extension tests.

**Comment by alexander-nitsche** [comment]
Ok, let's close this issue and open a new for "Reorganising testing chapters".

**Comment by alexander-nitsche** [comment]
See follow-up issue #1359 .
