### ISSUE TITLE
Rethink use of tables on some pages

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#644]
On mobile devices and with use of current theme, some tables will get cut off on the right. Also they might not always be the best solution to convey the information. 

* [ ] https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/GlobalValues/Constants/Index.html (see PR: #647)
* [ ] [Error and exception handling > Configuration](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/ErrorAndExceptionHandling/Configuration/Index.html) - here some content is cut off and you can't easily scroll horizontally (because scrollbar is at end of long table).

![table](https://user-images.githubusercontent.com/13206455/68224195-6eef8100-ffee-11e9-9b47-03535ec0305d.png)

**Comment by linawolf** [comment]
there is ongoing improvement in replacing tables and improving the styles. Cannot really be changed from this Manual alone
