### ISSUE TITLE
Document PageRenderer

### ISSUE THREAD

**Issue by susannemoog** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#665]
The PageRenderer is currently not documented at all, just referenced in various places.

So features like https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Feature-81464-AddAPIForMetaTagManagement.html can currently not be documented, as the main doc is missing.

**Comment by susannemoog** [comment]
see also https://github.com/TYPO3-Documentation/T3DocTeam/issues/108

**Comment by linawolf** [comment]
This topic has layn idle for a year
