### ISSUE TITLE
Documentation of t3editor missing

### ISSUE THREAD

**Issue by susannemoog** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#667]
t3editor currently has no documentation. To be able to document features like https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Feature-81901-ExtendT3editor.html we would first need to have some documentation at all.

**Comment by linawolf** [comment]
@DanielSiepmann are you still working on this?

**Comment by DanielSiepmann** [comment]
No, you can take over. Thanks for taking care @linawolf.

**Comment by linawolf** [comment]
See https://forge.typo3.org/issues/95836
