### ISSUE TITLE
Wrong admonition `info`

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#676]
There are currently 2 usages of `.. info::`, e.g. https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/commit/bbe78ecaa2006f1439ae6b5da357fd3be7ea1f73#diff-1943b212cb488298880ed4d8a7727cddR19-R22

all other doc repos should be checked as well. I am not sure if this was once valid or not? so either change those usages or add this admonition

**Comment by sypets** [comment]
I checked the other repos as well.
