### ISSUE TITLE
add not using declare_strict in ext_localconf/tables.php files

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#694]
Currently https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ConfigurationFiles/Index.html#best-practices-for-ext-tables-php-and-ext-localconf-php is missing information that you should not use ` declare(strict_types=1);`

see https://forge.typo3.org/issues/89691 for the related issue which I close in favor of this one

**Comment by susannemoog** [comment]
This has already been done by @mbrodala in commit https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/commit/5c81365221e3372c018ddc60aad1f169de6e5662#diff-76ba36f7ca1cc5d77b1e040d221874f3
