### ISSUE TITLE
Document the new Service.yml file

### ISSUE THREAD

**Issue by fawmi** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#702]
Almost all system extensions has got a Service.yml file since TYPO3 10. 
This file contains information regarding class autoloading which was previously defined in composer.  
What is the purpose of this file, should folder and namespace mapping coexist with composer.json's autoload property? 

This needs documentation.

**Comment by DanielSiepmann** [comment]
TYPO3 does use the Symfony component, so official documentation can be found at https://symfony.com/doc/current/service_container.html

TYPO3 related documenation is already available at https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/DependencyInjection/Index.html

Which parts do you miss?

**Comment by fawmi** [comment]
Ok I see now, I was disturbed with defining the autoload information in two different places.

In service.yml file 
```
  TYPO3\CMS\Belog\:
    resource: '../Classes/*'
```
And in composer.json file:
```
"autoload": {
		"psr-4": {
			"TYPO3\\CMS\\Belog\\": "Classes/"
		}
	},
```
But I see, they fulfill different purposes.
Maybe a short explanation of how are they related.

**Comment by sypets** [comment]
Additionally, I do think this is a good point about service.yml. We could add documentation:

* add service.yml in https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/FilesAndLocations/Index.html (could be a short text and point to Symfony docs and chapter about dependency injection)

**Comment by sypets** [comment]
I created a PR: #956

It does not contain much information now, but rather an overview of what is added to Services.yaml. The links point to the documention for DI and Events where the parameters are explained in depth.

My motivation is not so much adding information but having a central place for Services.yaml where you might land if you google it
