### ISSUE TITLE
No search results for "LocalConfiguration.php" "AdditionalConfiguration.php" and "DefaultConfiguration.php"

### ISSUE THREAD

**Issue by n3amil** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#716]
The search does not find any search result for

- LocalConfiguration.php
- AdditionalConfiguration.php
- DefaultConfiguration.php

I would expect to find the page https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/GlobalValues/Typo3ConfVars/Index.html#

I am able to find a lot of results without the .php file ending:
- LocalConfiguration
- AdditionalConfiguration
- DefaultConfiguration

**Comment by sypets** [comment]
I can reproduce this. 

See related issues:

* [Search doesn't work as it should](https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/issues/57)
* [Add additional help to search results page](https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/issues/84) (and PR: [[FEATURE] Add additional help and links to search results page](https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/pull/87))
* [Improve the Search results page](https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/issues/90)

**Comment by n3amil** [comment]
with the new search this specific issue for the core api search is fixed.

**Comment by sypets** [comment]
That's good to hear. Thanks you.
