### ISSUE TITLE
Change some formatting for long consecutive inline code texts

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#723]
**Update**: the new theme that is currently being developed will fix the non-breaking

--------------

This issue now handles the cases where inline code is not a good choice - whether breaking or non-breaking. 

----

~~Inline code is rendered in one line, non breaking. There is no scrollbar. With the new theme, this will often be outside the content area, e.g.~~

![inline](https://user-images.githubusercontent.com/13206455/72447445-a2e8de80-37b5-11ea-976b-8374da67d630.png)

see also [issue in theme](https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+inline)

In my opinion, very long inline texts are often not a good choice anyway. These should be replaced by code-blocks in most cases. In the example given here, they can be split up into separe entitites, e.g. `DEBUG`, `INFO`, `NOTICE` etc. 

This also makes it more readable. 

Often is is better to shorten the text or use additional formatting such as code-blocks, bullet lists etc.

**Comment by linawolf** [comment]
are you still working on this, @syspet? Has been idle since a year. I think we will work on this in the by-and-by. If you want to work on it again you can reopen it.
