### ISSUE TITLE
Type

### ISSUE THREAD

**Issue by theking2** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#725]
Not English: "How does it look like?"
English: "What does it look like?"  or "How does it look?"

Please change.

https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/PasswordHashing/Index.html#how-does-it-look-like

**Comment by sypets** [comment]
Thank you for your report. I will fix it. 

In the future, you might like to look at how to contribute: You can propose a change to any existing page in the documentation yourself by clicking "Edit me on GitHub". 

See:

* [How to Contribute to Official Documentation](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocsOfficial/Index.html)
