### ISSUE TITLE
Several issues with error and exception handling

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#738]
* [ ] The ["Error Handler"](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/ErrorAndExceptionHandling/ErrorHandler/Index.html
) page is slightly outdated:

> Logs error messages to \TYPO3\CMS\Core\Utility\GeneralUtility::syslog() 

The function syslog() is not called at all

* add overview (diagram?) what is called when depending on what (for example, from the error handler, an exception is thrown if error level is one of $GLOBALS['TYPO3_CONF_VARS']['SYS']['exceptionalErrors'])

* [ ] Deduplication: Error and exception handling
  * [TYPO3 Explained > CGL > Working with Exceptions](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/CodingGuidelines/CglPhp/PhpArchitecture/WorkingWithExceptions.html)
  * [TYPO3 Explained > Error and exception handling](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/ErrorAndExceptionHandling/Index.html)

**Comment by linawolf** [comment]
are you still working on it? If so please reopen. The topic has been idle since a year.
