### ISSUE TITLE
Pluggin an RTE needs an update

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#768]
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Rte/InTheBackend/PlugRte.html

> This page needs an update!
> Issue #78 states that this contents needs an update. It says:
> The documentation of “Plugging a RTE” seems to be deprecated since TYPO3 CMS 7.4. RTE registration isn’t made via $GLOBALS['TYPO3_CONF_VARS']['BE']['RTE_reg'] anymore. Instead the NodeFactory API is used.

**Comment by linawolf** [comment]
topic has been idle
