### ISSUE TITLE
Events API: How much to document? Should we link to the source?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#774]
I have been adding some of the [events to the existing API](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Hooks/Events/Index.html) and it is quite some work. Also, I think the API may change, new functions may be added etc Is this maintainable, or should we rather link to the source? 

I think it makes sense if we have examples, to add those. 

But, about adding and maintaining the API (if we basically just copy what is in the source) I am wondering if it might not be more efficient and easily maintainable to link to the source or API in some way. 

There is currently still an open issue about how to link to the source: TYPO3-Documentation/T3DocTeam#/66

Either via api.typo3.org or via GitHub. I think if we find a good way to do this, this might be a solution in addition to or instead of the API overview of the events.

**Comment by lolli42** [comment]
I don't think it makes sense to add each and every event: You'd add a section that will need constant changes to keep up with core development. I'd give some examples. People using events need to look for them in the code anyway to see what exactly they receive, where they are located and what you can do with them. Id does make little sense trying to document those in details, imho.

**Comment by sypets** [comment]
ok. Thanks for your input. 

The docs also now say "**noticable**" events, not all events. I will close here.
