### ISSUE TITLE
Outdated section of RTE registration

### ISSUE THREAD

**Issue by twity1337** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#78]
The documentation of "Plugging a RTE" seems to be deprecated since TYPO3 CMS 7.4.
[Link](https://docs.typo3.org/typo3cms/CoreApiReference/Rte/InTheBackend/PlugRte/Index.html) 

RTE registration isn't made via `$GLOBALS['TYPO3_CONF_VARS']['BE']['RTE_reg']` anymore.
Instead the `NodeFactory` api is used.

**Comment by marble** [comment]
I've placed this warning in the text at https://docs.typo3.org/typo3cms/CoreApiReference/Rte/InTheBackend/PlugRte/Index.html#plugging-a-rte

![018](https://cloud.githubusercontent.com/assets/307057/19987891/a26cddd4-a21d-11e6-9408-f47d54f76a12.png)

**Comment by sypets** [comment]
Section "Plugging a RTE" still contains update-note and has not been updated: https://docs.typo3.org/typo3cms/CoreApiReference/latest/ApiOverview/Rte/InTheBackend/PlugRte.html

**Comment by linawolf** [comment]
resolved by #923
