### ISSUE TITLE
Add more information about RouteEnhancers from Changelog (9.5 + 10)

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#784]
https://docs.typo3.org/m/typo3/reference-coreapi/9.5/en-us/ApiOverview/SiteHandling/Basics.html#routeenhancers

**Comment by susannemoog** [comment]
@sypets, what exactly do you want to add here? The main route enhancer docs are in the routing section, which is linked.

**Comment by sypets** [comment]
I think this is no longer relevant. There used to be some things only available in changelogs, specifically the page that now exists: https://docs.typo3.org/m/typo3/reference-coreapi/9.5/en-us/ApiOverview/Routing/AdvancedRoutingConfiguration.html#routing-advanced-routing-configuration
