### ISSUE TITLE
Coding Guidelines: Different definitions how to write folder name TSconfig

### ISSUE THREAD

**Issue by 3l73** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#794]
Inside of the [Coding Guideline](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/CodingGuidelines/CglTsConfig.html#tsconfig-coding-guidelines) the folder for TSconfig files is named as `TsConfig`

> TSconfig files are located in the directory `<extension>/Configuration/TsConfig`

- https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/CodingGuidelines/CglTsConfig.html#tsconfig-coding-guidelines

Inside of the reference of core api the folder is named as `TSconfig`:

> **Configuration/TSconfig/Page**
>       Page TSconfig, see chapter ‘Page TSconfig’ in the TSconfig Reference. Files should have the file extension .tsconfig.
> **Configuration/TSconfig/User**
>       User TSconfig, see chapter ‘User TSconfig’ in the TSconfig Reference. Files should have the file extension .tsconfig.

- https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/FilesAndLocations/Index.html

TYPO3 itself uses different types of folder structures. Sometimes the PageTS and UserTS files are located inside the configuration folder (see form extension) or the folder is written `TSconfig` as in extension frontend.

Which version of TSconfig is correct?

**Comment by 3l73** [comment]
Based on system extensions, there is no way how to figure out, which version is correct :(

Use of `PageTS`:
- https://github.com/TYPO3/TYPO3.CMS/tree/master/typo3/sysext/form/Configuration

Use of `TSconfig`:
- https://github.com/TYPO3/TYPO3.CMS/tree/master/typo3/sysext/backend/Configuration
- https://github.com/TYPO3/TYPO3.CMS/tree/master/typo3/sysext/frontend/Configuration

Use of `TsConfig`:
- https://github.com/TYPO3/TYPO3.CMS/tree/master/typo3/sysext/felogin/Configuration
- https://github.com/TYPO3/TYPO3.CMS/tree/master/typo3/sysext/linkvalidator/Configuration

**Comment by sypets** [comment]
If that is not done in the core consistently, that is something that could be reported in the core issue tracker: I created an issue: https://forge.typo3.org/issues/90667

Currently, I am not sure which way is correct. Your code should work either way but I would also rather use it consistently.

Have to wait for someone else to answer that.

**Comment by linawolf** [comment]
topic has been idle. if it is handled inconsistly in the core forge is the place to go.
