### ISSUE TITLE
Documentation of $GLOBALS['TYPO3_CONF_VARS'] (Global Configuration) setttings?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#797]
Error and exception configuration is documented on https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/ErrorAndExceptionHandling/Configuration/Index.html

Should we document all "Global Configuration" settings on a page?

Some related changelogs:

* `['BE']['passwordReset']` `['BE']['passwordResetForAdmins']` https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Feature-89513-PasswordResetForBackendUsers.html

**Comment by lolli42** [comment]
No. I think it would be better to hint the user to (install tool)  "Admin tools -> Settings -> Configure Installation-Wide Options" instead. This module gives all options including descriptions for each one.

**Comment by linawolf** [comment]
The install tool is no real documentation in my eyes, though it is important to mention it.

in the new index we can see the different places where TYPO3_CONF_VARS are being explained. In my eyes more detailed information would belong here: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/GlobalValues/Typo3ConfVars/Index.html#index-0

The page should concentrate less on the files to make the configuration in and more on the configurations themselves.

**Comment by sypets** [comment]
@linawolf What do you think is missing?

**Comment by linawolf** [comment]
Improved Structure, Links to where certain Options are described in depth. In my eyes there is too much concentration on the files here, where to do the configuration

**Comment by linawolf** [comment]
This has been idle
