### ISSUE TITLE
Create an extension development guide  or chapter? ("Extension Development Getting started)

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#798]
Moved from T3DocTeam

----

resources:

* https://wiki.typo3.org/Backend_Programming
* https://wiki.typo3.org/Overview_Developer_Manuals
* https://wiki.typo3.org/Extension_Development

This could be a subchapter in https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/CreateNewExtension/Index.html 

I would favor something that is not quite as lengthy as the Wiki pages.

**Comment by linawolf** [comment]
Will be part of the moving wiki content initiative
