### ISSUE TITLE
Document Fluid standalone view

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#802]
https://www.derhansen.de/2018/02/multiple-localized-fluid-standalone-views-in-one-request.html

Moved here from TYPO3-Documentation/T3DocTeam#85

**Comment by sypets** [comment]
This can be added as a subpage to the Fluid chapter: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Fluid/Index.html

**Comment by linawolf** [comment]
We don need to attak some real fluid manual (more then just a reference) it wont do to just add some things here and there.
