### ISSUE TITLE
Update TypoScript condition syntax examples to new v9 and v10 api.

### ISSUE THREAD

**Issue by tmotyl** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#803]
The page
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/edit/master/Documentation/ApiOverview/TypoScriptSyntax/Syntax/Conditions.rst

contains examples which will not work in v10, and are deprecated in v9.
Also some images whould need to be updated.

I think there should also be a dedicated page helping upgrade conditions from old to new syntax.
This is now a hard to find information and there are multiple blog posts about new syntax, mostly in german.

References:

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.4/Feature-85829-ImplementSymfonyExpressionLanguageForTypoScriptConditions.html

https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Conditions/Index.html

https://usetypo3.com/symfony-expression-language-in-typo3.html

https://wiki.sebkln.de/doku.php?id=typo3:about:conditions

https://stackoverflow.com/questions/8098850/typoscript-and-in-condition-not-working
https://stackoverflow.com/questions/53429969/typoscript-applicationcontext-condition-with-wildcards-or-sub-contexts-not-possi
https://stackoverflow.com/questions/57426653/typo3-typoscript-and-and-conditions-with-globalvar

**Comment by linawolf** [comment]
The examples have already been replaced. Working on the Migration part now

**Comment by linawolf** [comment]
Accidently closed

**Comment by linawolf** [comment]
This is merged
