### ISSUE TITLE
Document $tsfe->addCacheTags

### ISSUE THREAD

**Issue by susannemoog** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#809]
see issue https://forge.typo3.org/issues/67244

via TypoScriptFrontendController::addCacheTags it's possible for extensions to add cache tags to the current page easily that are automatically flushed when the datahandler gets changes for that page.

**Comment by linawolf** [comment]
@mbrodala Could you maybe add a PR for this?

**Comment by mbrodala** [comment]
@linawolf Here's my first stab on this: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/1266

**Comment by linawolf** [comment]
Merged
