### ISSUE TITLE
Remove mentioning records in page module

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#813]
https://docs.typo3.org/m/typo3/reference-coreapi/9.5/en-us/ApiOverview/Examples/TablesInPageModule/Index.html is outdated as this has been deprecated in 8.4 with https://forge.typo3.org/issues/77987 and removed with 9

**Comment by linawolf** [comment]
will be resolved with #1262
