### ISSUE TITLE
LocalConfiguration.php vs. AdditionalConfiguration.php

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#818]
What is currently the recommended practice for Global configuration that must be configured via PHP?

In #816 about logging configuration:

> Disabling as described only works in AdditionalConfiguration not in LocalConfiguration due to the way the configuration files are merged.

I would assume that goes for caching configuration etc. too?

I personally _only_ use AdditionalConfiguration.php for things like logging and cache configuration. I never enter anything directly in LocalConfiguration.php. 

There are several places in the docs, that recommend to use LocalConfiguration.php or they say you can use either.

### Caching framework:

> By default, most core caches use the database backend. Default cache configuration is defined in typo3/sysext/core/Configuration/DefaultConfiguration.php and can be overridden in LocalConfiguration.php.

> If specific settings should be applied to the configuration, they should be added to LocalConfiguration.php

https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/CachingFramework/QuickStart/Index.html

...

### Logging framework

does not mention any files?

https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Logging/Index.html

**Comment by lolli42** [comment]
Just as general idea: "AdditionalConfiguration.php" is the ugly child of configuration: The core eats it 'as is' and can't manage anything with it. In general, it should be avoided whenever possible to have it at all.
For instance, depending on what people put in there, it has the potential to kill even the install tool when upgrading.
Some alternatives are maybe .env files for example in some cases.
Imho, there should be a warning that AdditionalConfiguration is the last solution one should take if nothing else fits.

**Comment by linawolf** [comment]
@lolli42 would you like to make a PR about that?
