### ISSUE TITLE
Documentation updates related to Changelog 10.4

### ISSUE THREAD

**Issue by maddy2101** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#841]
# Breaking

*  [Breaking: 90660 - Registration of dashboard widgets changed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Breaking-90660-RegistrationOfWidgetsChanged.html) - see dashboard documentation

*  [Breaking: 91066 - Move interfaces of Dashboard](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Breaking-91066-MovedInterfacesOfDashboard.html) - see dashboard documentation

*  [Breaking: 91066 - Removed ButtonUtility](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Breaking-91066-RemovedButtonUtility.html) - not documented

# Features

* [x] [Feature: 83128 - Content Element Filter](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Feature-83128-ContentElementFilter.html)

* [x] [Feature: 87776 - Limit Restriction to table/s in QueryBuilder](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Feature-87776-LimitRestrictionToTablesInQueryBuilder.html)

* [x] [Feature: 89513 - Password Reset Functionality For Backend Users](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Feature-89513-PasswordResetForBackendUsers.html)

* [x] [Feature: 89573 - Allow flexible base url for slug fields in FormEngine](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Feature-89573-AllowFlexibleBaseUrlForSlugFieldsInFormEngine.html) - see TCAref TYPO3-Documentation/TYPO3CMS-Reference-TCA#273

* [x] [Feature: 90613 - Add language argument to page-related LinkViewHelpers and UriViewHelpers in Fluid](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Feature-90613-AddLanguageArgumentToPage-relatedLinkViewHelpersAndUriViewHelpersInFluid.html)

* [x] [Feature: 90826 - Compare backend usergroups](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Feature-90826-CompareBackendUsergroups.html)

* [x] [Feature: 90899 - Introduce AssetRenderer pre-rendering events](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Feature-90899-IntroduceAssetPreRenderingEvents.html)

* [x] [Feature: 90945 - PSR-14 event for LocalizationController when reading records/columns to be translated](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Feature-90945-PSR-14EventForLocalizationControllerWhenReadingRecordscolumnsToBeTranslated.html)

* [Feature: 91008 - Item grouping for TCA select items](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Feature-91008-ItemGroupingForTCASelectItems.html) - see TCAref: TYPO3-Documentation/TYPO3CMS-Reference-TCA#273

* [Feature: 91008 - Item sorting for TCA select items](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Feature-91008-ItemSortingForTCASelectItems.html) - see TCAref: TYPO3-Documentation/TYPO3CMS-Reference-TCA#273

* [x] [Feature: 91080 - Site settings as TypoScript constants and in TSconfig](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Feature-91080-SiteSettingsAsTsConstantsAndInTsConfig.html)

* [x] [Feature: 91122 - Introduce DocumentService as JQuery.ready substitute](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Feature-91122-IntroduceDocumentServiceAsJQueryreadySubstitute.html)

# Deprecation

* [x] [Deprecation: 88740 - ext:felogin pibase plugin related hooks](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Deprecation-88740-ExtFeloginPibasePlugin.html)

* [x] [Deprecation: 90147 - Unified File Name Validator](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Deprecation-90147-UnifiedFileNameValidator.html)

* [x] [Deprecation: 90377 - Param types $ref of method callUserFunction](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Deprecation-90377-ParamTypesRefOfMethodCallUserFunction.html)

* [x] [Deprecation: 90625 - Extbase SignalSlot Dispatcher](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Deprecation-90625-ExtbaseSignalSlotDispatcher.html)

* [x] [Deprecation: 90686 - Model FileMount](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Deprecation-90686-ModelFileMount.html)

* [x] [Deprecation: 90692 - FileCollection models](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Deprecation-90692-FileCollectionModels.html)

* [x] [Deprecation: 90800 - GeneralUtility::isRunningOnCgiServerApi](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Deprecation-90800-GeneralUtilityisRunningOnCgiServerApi.html)

* [Deprecation: 90803 - ObjectManager::get in Extbase context](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Deprecation-90803-DeprecationOfObjectManagergetInExtbaseContext.html) --> Extbase manual needs a general overhaul

* [x] [Deprecation: 90856 - Widget AutoComplete ViewHelper](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Deprecation-90856-WidgetAutocompleteViewHelper.html)

* [x] [Deprecation: 90861 - Image-related methods within ContentObjectRenderer](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Deprecation-90861-Image-relatedMethodsWithinContentObjectRenderer.html)

* [x] [Deprecation: 90937 - Various hooks in ContentObjectRenderer](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Deprecation-90937-VariousHooksInContentObjectRenderer.html)

* [x] [Deprecation: 90956 - Alternative fetch methods and reports for GeneralUtility::getUrl()](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Deprecation-90956-AlternativeFetchMethodsAndReportsForGeneralUtilitygetUrl.html)

* [x] [Deprecation: 90964 - LanguageService functionality and internal properties](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Deprecation-90964-LanguageServiceFunctionalityAndInternalProperties.html)

* [x] [Deprecation: 91001 - Various methods within GeneralUtility](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Deprecation-91001-VariousMethodsWithinGeneralUtility.html)

* [x] [Deprecation: 91012 - Various hooks related to TypoScriptFrontendController](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Deprecation-91012-VariousHooksRelatedToTypoScriptFrontendController.html)

* [x] [Deprecation: 91030 - Runtime-Activated Packages](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Deprecation-91030-Runtime-ActivatedPackages.html)

# Important

* [x] [Important: 18079 - pages.doktype restriction for frontend queries refined](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Important-18079-PagesdoktypeRestrictionForFrontendQueriesRefined.html)

* [x] [Important: 77715 - No more password trimming for third-party authentication services](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Important-77715-NoMorePasswordTrimmingForThird-partyAuthenticationServices.html)

* [x] [Important: 86343 - Replace jQuery.datatables with tablesort](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Important-86343-ReplaceJQueryDataTablesWithTablesort.html)

* [x] [Important: 89555 - Workspace-related database records contain the proper Page ID.](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Important-89555-Workspace-relatedDatabaseRecordsContainTheProperPageID.html)

* [x] [Important: 90285 - Fresh installs without constraint for typo3fluid/fluid will get version 3.0+](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Important-90285-FreshInstallsWithoutConstraintForTypo3fluidfluidWillGetVersion30.html)

* [x] [Important: 90897 - Remove bootstrap-slider](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Important-90897-RemoveBootstrap-slider.html)

* [x] [Important: 91079 - Various TypoScriptFrontendRenderer functionality is now internal](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Important-91079-VariousTypoScriptFrontendRendererFunctionalityIsNowInternal.html)

* [x] [Important: 91095 - Various methods and properties of Backend-related Core APIs now internal](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Important-91095-VariousMethodsAndPropertiesOfBackend-relatedCoreAPIsNowInternal.html)

* [x] [Important: 91099 - Flag identifier changed for SiteLanguage England](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Important-91099-ChangedFlagIdentifierForEngland.html)

**Comment by sypets** [comment]
btw. there is a script for automatically creating these issues including links from a changelog page: https://github.com/TYPO3-Documentation/t3docs-tools

`php generate-changelog-issue.php <url to changelog or version>`

**Comment by sypets** [comment]
I added all changelogs from https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Index.html# with the script. 

(I copied the previous content - in case that is required)

**Comment by susannemoog** [comment]
Checked all issues, pending PRs open for all missing things.
