### ISSUE TITLE
Add information since when @import is used instead of INCLUDE_TYPOSCRIPT

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#842]
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/TypoScriptSyntax/Syntax/Includes.html#typoscript-syntax-includes

This is the changelog: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Feature-82812-NewSyntaxForImportingTypoScriptFiles.html

---

e.g. as explained in https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/Index.html

Add

```
.. versionchanged:: version

   sometext
```

And link to changelog, e.g. 

`:doc:`t3coreapi:Changelog/10.0/Feature-88770-PSR-14BasedEventDispatcher``

**Comment by linawolf** [comment]
was merged
