### ISSUE TITLE
Documentation is missing information about the Locking API

### ISSUE THREAD

**Issue by markwatney2016** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#85]
A new Locking API was introduced with TYPO3 CMS 7.3 but there is no further information about it in the documentation.

Details: https://wiki.typo3.org/TYPO3.CMS/Releases/7.2/Feature#Feature:_.2347712_-_New_Locking_API

It may be helpful to describe:
- who (core developers, extension developers?) should use the Locking API
- why someone should use the Locking API
- which problems can be tackled by using the Locking API
- which problems can not be tackled by using the Locking API
- how the Locking API can/should be used
- possible problems and limitations when working with the Locking API

**Comment by sypets** [comment]
+1 

Information addressing not just developers but hosters (hosting and configuring TYPO3 regarding cache setup etc.) as well is welcome. Also, explaining the conceptual ideas would help in understanding the caching mechanism and locking better and can provide useful information.

Some questions that are not completely clear to me:
- The configuration option lockingMode (in LocalConfiguration) has been deprecated. Why? In some cases, it might be necessary to change the preferred locking mechanism (for example if the storage does not support the default flock on multiple servers). Or is there some way for configuring this? (besides writing your own LockStrategy class which is overkill if the provided classes are sufficient)
- The TYPO3 caching framework provides ways to change the default caching backend. This may cause problems if the lock mechanism is not configurable as well. For example if a RAM cache (e.g. memcache) is configured for page cache which is used locally on each server on a distributed server system but the typo3temp/locks is on a share. On the other hand if 1 database is used for page cache but each machine has it's own typo3temp directory the page cache is not locked correctly. For these (and other cases) it would help to provide some information, best practices and cross references to the caching framework documenation.

**Comment by sypets** [comment]
Some example where information already exists, that could be useful as a starting point, but partly needs to be validated if still applicable:

- locking api: https://github.com/TYPO3/TYPO3.CMS/blob/TYPO3_7-6/typo3/sysext/core/Documentation/Changelog/7.2/Feature-47712-NewLockingAPI.rst
- Starting here is a general discussion on lock / caching, however 2 years old: https://forge.typo3.org/issues/67246#note-7

**Comment by sypets** [comment]
I submitted a PR for this. It does not answer all questions posed above, but it is a start. 

However, I ran into some questions of my own: 

* AFAIK, there is still something missing for caching / locking. We've got all the lowlevel functionality (Caching Framework and Locking API), but the Caching Framework itself does no locking whatsover by itself. The calling application must do the locking, which is currently done for example in TypoScriptFrontendController.
* If I am correct, another layer that uses caching api with locking would be cool so every application (extension) does not have to reinvent the wheel. If not, it might be a good idea to give some examples for that as well in the docs and add that information to the Caching Framework chapter.

**Comment by liayn** [comment]
Correct. We thought about such a layer already, but it is almost impossible to have such a generic layer. The locking needed highly depends on what the application wants to implement. In the case of TSFE we have the extreme thing with a nested locking approach to get maximum performance an close to no wait-time.
Locking is indeed missing in a lot of parts in the core, not only around caches.
I'm open for any suggestion regarding such a generic layer though.

**Comment by sypets** [comment]
@liayn Maybe, for the extension developers, we can add code examples / best practices to the "TYPO3 explained" docs. 

We (I @ work) use the Caching Framework in an extension which we developed here and I always assumed the Caching Framework used locking internally (not that anyone ever said this). Well, it doesn't and I think I should fix this now in my extension. If I'm adding the code now, it's probably not much extra work to create a PR adding some of that to the documentation and maybe you or Lolli can have a look.

For using (caching with) locking in the core / general layer: That does sound like not an easy job indeed. The more I document and read through the code, the more I hope I can make useful suggestions, but too early for me. Not an expert on this. If you can take that topic up with core team / decisions, would not be unhappy about that.

If anyone can point to some general concepts / good resources (must not be TYPO3 specific), might also be helpful.

**Comment by liayn** [comment]
The thing is that it depends on how you use the cache. Is it a simple reader-writer problem? Are there potentially multiple writers? etc etc

In terms of extension dev support I don't see the problem in the code-wise mechanics but more on the educational level. People often do not keep in mind that a website is an application with a lot of parallel processes. PHP too often gives you the impression one works in its own ecosystem. This assumption is broken in the second one reads or writes to a DB or a file.

For instance in the core itself:
- Cache garbage collection does not lock readers
- Fluid template eviction does not lock. high load leads to failing `unlink` calls
- BE must actually use transactions when saving a tt_content record as multiple tables are involved. (again separation of readers and writers)

So there's endless amounts of work to be done. Start where it hurts most.

**Comment by sypets** [comment]
PR was merged: https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/LockingApi/Index.html
