### ISSUE TITLE
Extended crowdin FAQs: explain useful ignores in .crowdin.yaml

### ISSUE THREAD

**Issue by josefglatz** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#859]
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/edit/master/Documentation/ApiOverview/Internationalization/TranslationServer/Crowdin/Faq.rst

**Comment by josefglatz** [comment]
@georgringer is it ok to explain two points:

* add (another) example for crowdin.yaml when ignoring translated files
* add info for the mode without adding translated files to the own extension (and only using the TYPO3 language packs downloads)

**Comment by georgringer** [comment]
yes @josefglatz , pls go ahead ;)

**Comment by linawolf** [comment]
@josefglatz are you still working on this?

**Comment by georgringer** [comment]
would suggest closing this for the time being

**Comment by linawolf** [comment]
Ok, closing now. You guys can always reopen or open another issue
