### ISSUE TITLE
Remove reference to pages_language_overlay.php in description of adding new page type for version >= 9.5

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#877]
https://docs.typo3.org/m/typo3/reference-coreapi/9.5/en-us/ApiOverview/PageTypes/Index.html#create-new-page-type

**Comment by sypets** [comment]
This is already done for master and 10.4, but not for 9.5. PR in progress ...

**Comment by linawolf** [comment]
Merged
