### ISSUE TITLE
Documentation updates related to Changelog 10.4.x

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#885]
**Because Changelogs are currently not being rendered, we added newer links to source code instead of rendered version!**

---

Workflow for updating docs based on Changelog is documented on https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/HowToUpdateDocs.html

----

Issue created by[ t3doc-tools](https://github.com/TYPO3-Documentation/t3docs-tools):

    php generate-changelog-issue.php "https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Index.html"

-----

# Breaking

# Features

* [x] [Feature: 91132 - Introduce User Settings JavaScript Modules Event](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4.x/Feature-91132-IntroduceUserSettingsJavaScriptModulesEvent.html)

* [x] [Feature: 90728 - Add FluidEmail option to EXT:form EmailFinisher](https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Documentation/Changelog/10.4.x/Feature-90728-AddFluidEmailOptionToEXTformEmailFinisher.rst)

# Deprecation

# Important
* [x] [Important: 82489 - Use dedicated property to hide newRecordLink button](https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Documentation/Changelog/10.4.x/Important-82489-UseDedicatedPropertyToHideNewRecordLinkButton.rst)

* [x] [Important: 91070 - SMTP transport option ‘transport_smtp_encrypt’ changed to boolean](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4.x/Important-91070-SMTPTransportOptionTransport_smtp_encryptChangedToBoolean.html)

* [x] [Important: 91117 - Use GlobalEventHandler and ActionDispatcher instead of inline JS](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4.x/Important-91117-UseGlobalEventHandlerAndActionDispatcherInsteadOfInlineJS.html)

* [x] [Important: 91132 - Avoid JavaScript in User Settings Configuration options](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4.x/Important-91132-AvoidJavaScriptInUserSettingsConfigurationOptions.html)

* [Important: 92336 - Discarding records in workspace module hard deletes them](https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Documentation/Changelog/10.4.x/Important-92336-DiscardingRecordsInWorkspaceModuleHardDeletesThem.rst) - no documentation change necessary

* [Important: 92356 - DataHandler performance improvements](https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Documentation/Changelog/10.4.x/Important-92356-DataHandlerPerformanceImprovements.rst) - no documentation change necessary

**Comment by susannemoog** [comment]
Done :)
