### ISSUE TITLE
2 Deprecation chapters

### ISSUE THREAD

**Issue by IndyIndyIndy** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#910]
There are two very similar chapters on deprecation:
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Deprecation/Index.html
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/CodingGuidelines/CglPhp/CodingBestPractices/HandlingDeprecations.html?highlight=deprecation

These should be merged together.

**Comment by lolli42** [comment]
+1 the part within cgl chapter looks better.

**Comment by sypets** [comment]
Related: 

* #274 
* https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow/issues/152

There are currently at least 4 places where deprecation is described (with different focus):

* Contribution Guide: [How to deprecate classes, methods, arguments and hooks in the TYPO3 core](https://docs.typo3.org/m/typo3/guide-contributionworkflow/master/en-us/Appendix/HowToDeprecateThings.html) - specific to core development
* CGL: [Handling Deprecation](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/CodingGuidelines/CglPhp/CodingBestPractices/HandlingDeprecations.html) - also specific to core development
* TYPO3 Explained: [Deprecation](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Deprecation/Index.html) : is not core specific and handles some things the other resources do not, e.g. disabling deprecation logging, deprecating functions in extension. 
* Wiki: [deprecation log](https://wiki.typo3.org/Deprecation_Log): is oudated. Can be either removed and redirected or ignored for now

The part in the CGL handles how to deprecate things in the core. I think core-specific documentation should be moved to contribution guide. 

The second part "[Deprecate Functions in Extensions](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Deprecation/Index.html#deprecate-functions-in-extensions)" in Deprecation chapter in T3Ex is the same as in the core, I would just refer to the core contrib documentation.
