### ISSUE TITLE
missing documentation about options

### ISSUE THREAD

**Issue by steffenk** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#94]
The doc only give one example for rte using
`'defaultExtras' => 'richtext[]'`

Missing is that it's possible to add it like this to get a full options rte:
`'defaultExtras' => 'richtext[*]'`
some details what is possible to insert here would be useful as well.

One problem i found was about file links in rte, it only rendered "file:1234" in FE. I was able to fix it this way:
`'defaultExtras' => 'richtext[]:rte_transform[mode=ts_links]'`

**Comment by marble** [comment]
Cool. I'll add that somewhere soon!

**Comment by marble** [comment]
Steffen, can you tell which TYPO3 versions are affected? 6.2? 7.6? 8-dev?

**Comment by steffenk** [comment]
its tested on 7.6, so should be with all >7 starting to use defaultExtras. Didn't checked version 8 yet.

**Comment by marble** [comment]
Thank you very much. I've integrated it like this:
https://docs.typo3.org/typo3cms/CoreApiReference/Rte/InTheBackend/Index.html#get-a-full-options-rte
![019](https://cloud.githubusercontent.com/assets/307057/19988820/c0ed3614-a222-11e6-8340-5eca7bacf753.png)
