### ISSUE TITLE
FlexForm displayCond / onChange - possible documentation error

### ISSUE THREAD

**Issue by audef1** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#940]
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/FlexForms/Index.html#display-fields-conditionally-displaycond

In the documentation it says, that the displaycondition should go inside the config element.
When doing so nothing happens. When inserting displayCond alongside the config / title elements it works just fine.

Same thing with the onChange tag. https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/FlexForms/Index.html#reload-on-change

> This element is optional and must go inside the <config> element.

**Comment by mbrodala** [comment]
This was fixed by #939
