### ISSUE TITLE
remove reference to condensedMode

### ISSUE THREAD

**Issue by tmotyl** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#96]
file https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/blob/5ba7d08dfa028f48b6b5ce7934ee6bb24b8db680/Documentation/ApiOverview/BackendUserObject/Index.rst
contains reference to the condensedMode setting which is long gone.
see https://forge.typo3.org/issues/24585

**Comment by Chrissitopher** [comment]
Thanks for the note! I have just fixed the issue!
