### ISSUE TITLE
Document all functions in Environment or at least point out that there are more than currently listed

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#975]
Current docs page:

* https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Environment/Index.html

usetypo3

* https://usetypo3.com/9lts-api-classes.html

Additionally, I think it would be helpful to add the following links:

*  to the usetypo3 blog entry
*  to the [Context](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Context/Index.html) page

**Comment by linawolf** [comment]
they are documented in current master
