### ISSUE TITLE
Task: 65770 - Enable EXT:impexp to include presets in export (11, 10.4)

### ISSUE THREAD

**Issue by alexander-nitsche** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#999]
Name | Value
-- | --
Type: | Task
Merging into: | master, 10.4
Gerrit: | [65770](https://review.typo3.org/c/Packages/TYPO3.CMS/+/65770)

**Comment by linawolf** [comment]
@alexander-nitsche could you make a PR about this?
